### ISSUE TITLE
admin update overwrites robot.txt

### ISSUE THREAD

**Issue by PASDATA** [getgrav/grav-plugin-admin#100]
just used the admin plugin to update to 0.9.38 and it overwrites the robots.txt file - would be better if it didn't

**Comment by rhukster** [comment]
This is actually an issue for the core 'grav' repository as it's related to the update package.

We do plan on removing some more files from the update package (.htaccess, robots.txt etc), but during the beta we wanted to make sure that any important updates got out there, rather than relying on users to fix these things themselves.

With the 1.0 release and going forward i'll feel more comfortable not being able to provide updates for these files.

**Comment by PASDATA** [comment]
Ok, I understand. Thanks for the update.

**Comment by rhukster** [comment]
Actually i've fixed this for the next update.  We're pretty close to 1.0 and we've not had reason to update these files in quite some time.
