### ISSUE TITLE
Feature request: Ability to use folders without md-files

### ISSUE THREAD

**Issue by Sogl** [getgrav/grav-plugin-admin#1000]
Sometimes I need to store images and other files outside the root page folder. See:
![image](https://cloud.githubusercontent.com/assets/7556290/23290776/9001d1d0-faa7-11e6-96c5-68175f230ea8.png)

I don't need any md in it just because sometimes needs to delete files via FTP and can accidentally delete it.

But without md Media Manager don't work: 
`NOTE: You cannot add media files until you save the page. Just click 'Save' on top`

Also I can't create nested folders without putting md in EVERY folder. See:
![image](https://cloud.githubusercontent.com/assets/7556290/19422774/2938c79a-9465-11e6-8b61-bb79aa46a1a0.png)
Grav don't have any option to specify template for nested folders.

Any ideas?

**Comment by rhukster** [comment]
This is indeed a limitation of the admin plugin.  I know when we originally built the admin it was not possible to have a folder without a file.  Much later we added the ability to add a folder directly.  Now it makes sense to investigate if we can confirm the surrounding folder exists and use that rather than if the page exists to toggle if the field should be shown.

**Comment by rhukster** [comment]
Should be fixed with next Grav+Admin plugin release.. just checks on folder existence now.
