### ISSUE TITLE
sweep plugins to remove unwanted plugins....

### ISSUE THREAD

**Issue by 4evermaat** [getgrav/grav-plugin-admin#1003]
When removing a theme, grav will check to see if you can remove plugins that are no longer needed.  But then you must remove them one by one.  What if you don't remove all the unneeded plugins at the time, but later decide you want to remove unneeded plugins?

how do I perform a check to see if plugins are needed?   I'm looking for a button that I can click 'check dependencies' 'remove unused plugins' or something like that.

**Comment by rhukster** [comment]
The question is how would Grav know what is unwanted and what was not? A lot of plugins are simply passive and will display data only when they are accessed via a Twig template.  There's really no way to know if there's a reference or not short of regex'ing every `.twig` file and check for existence of a reference.  That assumes that Grav would know what that reference would look like.

 I just don't see how this would be possible programmatically.  Makes much more sense for the developer to do this manually because they are the ones that know if they have used a plugin or not.

**Comment by 4evermaat** [comment]
well, when I deleted a theme, grav somehow scanned the other themes to see what their dependencies were and then prompted me to delete the unused plugins.   So that is why I brought it up.
