### ISSUE TITLE
Custom form that saves data gives an error

### ISSUE THREAD

**Issue by Flibio** [getgrav/grav-plugin-admin#1021]
Hello, I have recently created a plugin that adds a page to the admin panel. On the page it has a form that allows you to add a new item to a data list. However, whenever I add the data an error appears. The data is still saved though. I have based my code off of the [FlexDirectory](https://github.com/trilbymedia/grav-plugin-flex-directory) plugin.

The error says: "Data type 'speakers/edit' doesn't exist!"

- Note: `speakers/edit` is the address of the editing page.

Here is the code I am using in my plugin: [Link to Gist](https://gist.github.com/Flibio/1d098f94588504fc54684a5824662d43).

**Comment by rhukster** [comment]
Ok, i've looked over this 'quickly', and it appears you've taken 'parts' of the flex directory plugin and copied it over and adapted it in your plugin.  There is undoubtedly something that has not been updated during that move.  Unfortunately I really don't have time to debug this as it's custom code, and will require quite a bit of effort to track down.  It's not a bug in Grav or the Admin plugin, it's really something in your custom plugin.

My suggestion is rather than starting from scratch and trying to merge bit of flex directory in, why not start with flex directory and just edit the blueprints/twig as the `README.md` outlines to suit your needs. 

If you need more modifications, then take flex directory and rename all the bits to match what you need.  This is going to be a bit of a process and I recommend changing as little as possible as you will undoubtedly end up in the same situation.

i originally took another plugin that was hardcoded for a particular client and made it more 'flexible' and released it as the somewhat generic `flex-directory` plugin.  A lot of work went into making this as simple to modify as possible, but it still requires significant changes if you start changing the names of core things.

If you still need help, then our professional services division (Trilby Media) on a per hour consulting basis.
