### ISSUE TITLE
Can't create account in admin or login after creating account via CLI

### ISSUE THREAD

**Issue by selfagency** [getgrav/grav-plugin-admin#1027]
I'm on a fresh Grav install. I installed using Composer. I installed the admin plugin using GPM. When I load my site (via PHP 7.0's builtin web server), the admin account creation page loads. After filling out the form and clicking `Create User`, the form refreshes to the same state and does not create a user (`no admin accounts could be found`). When I run `bin/plugin login newuser` from the command line, an account is created (a corresponding, populated .yaml file exists in `user/accounts`), but when I return to the admin console, I again get the account creation page and the message `no admin accounts could be found`. There is no change after running `bin/grav clear-cache`.

**Comment by OleVik** [comment]
What OS are you on? Can PHP read the files it needs to read within Grav? Check out [this article in the Docs](https://learn.getgrav.org/troubleshooting/permissions).

**Comment by selfagency** [comment]
macOS 10.12.3

I ran the permissions script on the page you shared

```
#!/bin/sh
chown -R daniel:staff .
find . -type f | xargs chmod 664
find ./bin -type f | xargs chmod 775
find . -type d | xargs chmod 775
find . -type d | xargs chmod +s
umask 0002
```

I got back

```
chmod: ./user/plugins/events/docs/css/phpdocumentor-clean-icons/Read: No such file or directory
chmod: Me.txt: No such file or directory
```

When I start up the web server again, I get the same result. It can't read my user file.

**Comment by flaviocopes** [comment]
I think the problem is permission of the web server is not the same as the owner of the files. So, the web "create account" form cannot write or read to the file system.

Being on a Mac, try MAMP, which is known to get the permissions in the right way.

**Comment by DjZU** [comment]
For the record, I faced the same issue of getting "no admin accounts could be found" when migrating my Grav installation. Permissions, PHP version, Nginx configuration, mount options have been checked. I noticed that running bin/grav clearcache would not clear anything and after a sleepless night I could find out that the reason was that the path of my Grav installation was containing brackets. I renamed this and the problem was solved. 
This bracket issue doesn't look new: [https://www.php.net/manual/en/function.glob.php#86425](url)
I guess it's a bad practice to use such characters in a webserver config anyway.
