### ISSUE TITLE
Language selector on admin panel does not work in Edge

### ISSUE THREAD

**Issue by MathiasMagnus** [getgrav/grav-plugin-admin#1038]
When I try to edit the contents of a page in a multi-lingual site while using Edge, I click the lang dropdown, it shows the options, but when I click it, nothing happens. The same in Opera works as expected.

**Comment by rhukster** [comment]
Can anyone with IE/windows help with this one?

**Comment by MathiasMagnus** [comment]
I guess you are looking for someone capable of developing too, not just testing.

**Comment by rhukster** [comment]
Well it's probably just a CSS fix but ya. Much easier to fix if you run windows.

**Comment by TomOne** [comment]
I think this problem exists because of the missing `form` attribute support in MS Edge.

The provided [form attribute polyfill](https://github.com/getgrav/grav-plugin-admin/blob/fb24c9595231b8cde4f82fe098e7c926e868316b/themes/grav/js/form-attr.polyfill.js) seems to only trigger after a form submit. The language switching buttons don’t trigger a form submit and therefore the polyfill is never executed.

Running

``` JavaScript
$('#admin-lang-toggle').prependTo('#blueprints')
```

in the browser console to temporarily move the language buttons inside the `#blueprints` form makes language switching work in MS Edge.

I’ll try to find a fix for this issue and make a pull request.

**Comment by MathiasMagnus** [comment]
Much appreciated. Thanks!

**Comment by TomOne** [comment]
I was able to fix this with #1213.

**Comment by TomOne** [comment]
Thanks. Fixed in #1213
