### ISSUE TITLE
Convert non-alphanumeric characters to Unicode

### ISSUE THREAD

**Issue by butchewing** [getgrav/grav-plugin-admin#1086]
Could we auto convert non-alphanumeric characters in a frontmatter slug to Unicode on submit? This would allow for Multi-Language Routing for any language. 

Example:
`slug: المعتقدات`

**Comment by flaviocopes** [comment]
Can you make a small example of what you're not able to do right now, and what would be possible with the change you requested?

**Comment by OleVik** [comment]
This was discussed on Slack yesterday. An example would be URLs which do not use latin characters, like this news article on Al Jazeera:

`aljazeera.net/news/international/2017/4/24/مسجدي-علاقات-إيران-والعراق-لابد-أن-تكون-أكثر-جدية`

The browser will interpret that into unicode:

```
http://www.aljazeera.net/news/international/2017/4/24/%D9%85%D8%B3%D8%AC%D8%AF%D9%8A-%D8%B9%D9%84%D8%A7%D9%82%D8%A7%D8%AA-%D8%A5%D9%8A%D8%B1%D8%A7%D9%86-%D9%88%D8%A7%D9%84%D8%B9%D8%B1%D8%A7%D9%82-%D9%84%D8%A7%D8%A8%D8%AF-%D8%A3%D9%86-%D8%AA%D9%83%D9%88%D9%86-%D8%A3%D9%83%D8%AB%D8%B1-%D8%AC%D8%AF%D9%8A%D8%A9
```

As far as I can tell, all modern browsers do this behind the scenes, and you'd only notice the operation if you copied a part of the URL from the address-bar and pasted it as raw text - copying the whole URL encodes it. And since any URL can contain unicode, allowing unicode-characters rather than just latin-characters allows slugs in all languages, at least insofar as there are no conflicts with accents and the like.

**Comment by butchewing** [comment]
Take look at [Laravel Eloquent sluggable for persian & arabic labguages](https://github.com/morilog/eluquent-sluggable-persian). Or, it may be as simple as:

```
<?php
function slugify($string) {
    $string = transliterator_transliterate("Any-Latin; NFD; [:Nonspacing Mark:] Remove; NFC; [:Punctuation:] Remove; Lower();", $string);
    $string = preg_replace('/[-\s]+/', '-', $string);
    return trim($string, '-');
}

echo slugify("Я люблю PHP!");
?>
```
Found [here](http://php.net/manual/en/transliterator.transliterate.php#110598).

**Comment by rhukster** [comment]
That solution requires the `Pecl::intl` package for the `transliterator_transliterate()` method.
