### ISSUE TITLE
Padding for expert view toggle buttons to low

### ISSUE THREAD

**Issue by jackmu95** [getgrav/grav-plugin-admin#1089]
Depending on the chosen language, the padding in the `tabs-nav` for the `admin-topbar` is to low.

**Englisch**
![image](https://cloud.githubusercontent.com/assets/2737132/25373123/ad084c4e-2998-11e7-91be-5f96966f0ad5.png)

**German**
![image](https://cloud.githubusercontent.com/assets/2737132/25373130/b4d14b06-2998-11e7-9d3a-6b004ba97c44.png)

About 380 Pixel would fit for German but because this depends on the language, it would be better to calculate it dynamically.

**Comment by rhukster** [comment]
This is a bit tricky, because the tabs are actually rendered first, and have no clue abut the expert/normal and language dropdown which is coming from the content but is absolutely positioned.  I'll have to think about this one.

**Comment by OleVik** [comment]
With the buttons and dropdown absolutely positioned, is there not a permanent risk of collision? They could be scaled hierarchically, where level 1 has two elements: One 80% width for Tabs and one 20% width for the Remainder. On level 2 Tabs are distributed equally through flex or just inline-blocks, and the Remainder allocates 10% width for the language-dropdown, and 45% width for each button.

For the buttons within Remainder on level 2, overflow is hidden so that on smaller resolutions or when there is a conflict in width, as much as possible text is shown from each button - but they will not barge into the Tabs.

**Comment by rhukster** [comment]
Well my plan is to have a twig block position i can inject the selectors into. That way we can use flex box for the whole thing and things will always fit nicely.

**Comment by rhukster** [comment]
Ok, it's just not possible with the approach i had hoped to use as the tabs are generated by the blueprint and there's no way to extend them in there.  I have a bit 'hackish' but effective solution that just sets the margin based on the width of that block via JavaScript.
