### ISSUE TITLE
Can't delete responsive images added in the Page Media area

### ISSUE THREAD

**Issue by jpfleury** [getgrav/grav-plugin-admin#111]
**Steps:**

- Add an image named `image@3x.jpg` by uploading it in the Page Media area.

- When the image is uploaded, save the page.

- Put the cursor over the image in the Page Media area and click *Delete*.

- Click *Continue*.

**Result:** we have this error:

> An error occurred while trying to remove the file **image.jpg**
> 
>     File not found: image.jpg

**Comment by rhukster** [comment]
This kinda goes along with the other responsive image issue #109

**Comment by flaviocopes** [comment]
@rhukster when uploading `image@3x.jpg`, the image is stored as `image@3x.jpg` in the page folder. Before saving, in the Admin Page Media it's listed as `image@3x.jpg`. After saving it's listed as `image.jpg`. 

I think that's correct, 
When deleting that image, should it try to delete all the possible versions, in short:

- image.jpg
- image@1x.jpg
- image@2x.jpg
- image@3x.jpg

?

**Comment by rhukster** [comment]
The retina-ness should be transparent when using the images in your content.. So if you have uploaded an `image@3x.jpg` image, you actually only use and reference the `image.jpg` in your tags. This is because Grav is handling writing out the string with all the various versions appropriate for your browser.

However it might be nice to have a little flag or badge on the image in the media tray, so you know it's a @3x image.

And you are correct, if you delete the image, it should delete all versions of it that grav has created.

**Comment by flaviocopes** [comment]
So it should also list it as `image.jpg` right after the upload (before saving), instead of `image@3x.jpg`

**Comment by flaviocopes** [comment]
That should also fix #109

**Comment by rhukster** [comment]
yes, it should list as image.jpg, but have a badge saying @3x.  I think this is the best way to represent it, and should work properly when adding to the markdown via drag-n-drop.
