### ISSUE TITLE
The folder name field allows empty value

### ISSUE THREAD

**Issue by lauroguedes** [getgrav/grav-plugin-admin#1146]
If saving with the empty field will erase the file if the numeric prefix is marked as unavailable. If this same prefix is hailed the system will throw an error in both the admin and the page, check the error in the image.

![errror-folder-name-empty](https://user-images.githubusercontent.com/3677780/27542245-122996d8-5a5d-11e7-9626-459d3b206d7c.png)

[Suggestion] if the field is empty, when saving the page the system would pick up the page title and write it as slug in the folder name field

**Comment by david-szabo97** [comment]
I think adding a simple `required: true` to the folder input would fix this.

Just wondering why the page blueprint is included with the grav core rather than the admin plugin. @rhukster ? (https://github.com/getgrav/grav/blob/develop/system/blueprints/pages/default.yaml) Isn't this one should be in the admin plugin's repo? I spent like 10 minutes to find it in the admin plugin's repo without success :smile: All of those blueprints are unrelated with the core. (config/media.yaml, config/site.yaml etc.) Is there a reason for putting them in the core repo? Maybe it is related to how overriding works?

**Comment by lauroguedes** [comment]
This don't work, I tried this. I add, but it show a mesage that field is required same being filled.

**Comment by flaviocopes** [comment]
This is happening when adding a new page/ folder? 

You should see a client-side check. Which browser are you using?

![screen shot 2017-06-28 at 13 27 40](https://user-images.githubusercontent.com/11783388/27634959-a06d3874-5c05-11e7-9172-331f51f10e2a.png)

**Comment by flaviocopes** [comment]
@david-szabo97 some blueprints need to be in the core, not sure if all of those are required. But open a new issue to discuss this separately, as it's a different topic

**Comment by lauroguedes** [comment]
It's not the time you're going to create a page, it's time to edit. Do the test, create a page and then click to edit and leave this field blank. The error caught was in page editing and not in creation.

**Comment by flaviocopes** [comment]
@lauroguedes got it, thanks for reporting!

**Comment by flaviocopes** [comment]
(change reverted as it caused an error while saving)
