### ISSUE TITLE
[Suggestion] Modular page and module disambiguation 

### ISSUE THREAD

**Issue by paulmassen** [getgrav/grav-plugin-admin#1174]
I just thought there could be a way to diffentiate between the modular page itself, and the sub-modular page.

Maybe it's just me, but I always have a hard time explaining to the end user the difference between a modular page and submodular page.

Was it considered to rename them as "module" or something similar?
Here is some denomination that would be more self-explanatory in my opinion:

- Modular Brick
- Modular Block
- Module Block
- Modular Component

Also, when clicking on the dropdown and "add modular", shouldn't the `pages` field be limited to displaying modular pages that would be able to host the "module" only?

I hope I am clear enough and that improving this naming could be useful to other!

Thanks,

Paul

**Comment by Kangouroops** [comment]
I agree. Modular item or even sub-modular could do the job. :)

> Also, when clicking on the dropdown and "add modular", shouldn't the pages field be limited to displaying modular pages that would be able to host the "module" only?

And if you are on a modular page, maybe the only parent available should be the one you where on ?

**Comment by OleVik** [comment]
This has been discussed at various times, and what I perceive the consensus to be is this: A modular page contains modules. Semantically this is more descriptive than block, which is a concept used extensively in Twig and theming, or component, which is extensively used almost everywhere in programming. Thus, a module is a part of the whole of a modular page, and a modular page is a part of the Grav-installation. Or reversed: A page can be modular, where it consists of several modules that each behave differently.

To distinguish them from child-pages, the modular-template defines how each module behaves, whereas a parent-page does not necessarily do this for its child-pages.

**Comment by paulmassen** [comment]
Thanks OleVik, so if you use "module" yourself, is there a reason why the term "module" is not used to designate it in Grav, neither in the docs?

**Comment by OleVik** [comment]
Because the description of the concept of a modular page was last updated to years ago? As I said, it's been discussed and I have a perception of a consensus, mainly from a discussion in May where both sub-page and block were evaluated as insufficient due to how modular pages operate.

I agree that the nomenclature does not lend itself to conceptual clarity for end-users at the moment, but consider this: A modular page is singular, not subordinate or superior to any other type of page; each part of a modular page can only work within a modular page, not as a child-page and typically not as a component inserted elsewhere; the modular template is constructed like a component with several parts.

Hence, since a "component" can be abstracted into a "system", with all its "parts" subordinate to it, a "modular page" with "module"-parts is semantically viable because the modular cannot be abstracted. It is a standalone page not defined by its relationship to the system vertically, only horizontally, and as a page it does not integrate with other pages. Its modules only relate to the modular, not to any other page.

Beyond that technical clarification/rambling, I think a humanly-readable clarification in the docs is warranted, that distinguishes what a modular page is _as opposed to_ a regular page with child-pages.

**Comment by OleVik** [comment]
Ignore most of those references, [#479](https://github.com/getgrav/grav-learn/issues/479) is actual. Is [this](https://github.com/OleVik/grav-learn/blob/a49073e3aede5c0872a5eb442ee61b344c6ebf07/pages/02.content/09.modular/docs.md) an adequate clarification @paulmassen? I rewrote several parts of that page and "Pages" to clarify the distinction between Modular Pages and regular Pages, and added the "Modules" nomenclature for clarity.

Whatever word is more apt, "Modular Pages" within a "Modular Page" is certainly inadequate.

**Comment by flaviocopes** [comment]
Good points, I agree on the confusion about this topic. Module feels good to me.

**Comment by paulmassen** [comment]
excellent @OleVik I feel like this will helps end-users a lot for understanding this concept

**Comment by rhukster** [comment]
@OleVik's rework of the learn docs has been merged, so closing this issue...

**Comment by paulmassen** [comment]
Should we rename "Add modular" to "Add Module" ? https://github.com/getgrav/grav-plugin-admin/blob/develop/languages/en.yaml#L36
