### ISSUE TITLE
Only 1 page state is shown for each page

### ISSUE THREAD

**Issue by phivk** [getgrav/grav-plugin-admin#1188]
The page legend includes the following page states:
* `Visible` (blue)
* `Non-Routable` (red)
* `Non-Visible` (grey)
* `Modular` (purple)

While these states aren't mutually exclusive, the 1 single cirlce left of the page name shows only one of them, and is thus unable to express the full state of the page. (Only on hover is the full state revealed as text labels). 

In the example below the purple circle only shows that the modular 'Features' page is `Modular`, but hides that it is `Non-Routable`, `Non-Visible` and `Published`.

![screen shot 2017-08-03 at 18 07 59](https://user-images.githubusercontent.com/902958/28931542-c0e8aa9c-7876-11e7-856c-0abd5628930e.png)

It would be great to see all full page states at a glance, e.g. which modular pages are `Published` and which aren't.

**Comment by phillchill** [comment]
I made a quick mockup of how the colours in the current Page Legend could be used to communicate full page state.

Firstly, I believe the states in the Page Legend could be more aptly expressed as:

![page-legend](https://user-images.githubusercontent.com/902958/28932020-60256d1a-7878-11e7-8bb6-33285c08c5ef.jpg)

Then the Home page can be displayed as:

![home-collapsed](https://user-images.githubusercontent.com/902958/28932071-87c0d576-7878-11e7-8241-a0fa47bde419.jpg)

And uncollapsed as:

![home-uncollapsed](https://user-images.githubusercontent.com/902958/28932086-91bec07e-7878-11e7-8cdf-c2c32e930421.jpg)

**Comment by rhukster** [comment]
I appreciate the effort that has gone into this, but I feel like the many indicators actually makes things harder to read because the more indicator circles, the more complex the pattern is to decipher.  I have a tough time even determining what's different between each item at first glance and have to to visually compare each row to the one above or below to see the differences.

I'm really not sure what the best solution is here, i'm going to have a think over the weekend...

**Comment by phillchill** [comment]
@rhukster thanks for your initial feedback. 

> the many indicators actually makes things harder to read because the more indicator circles, the more complex the pattern is to decipher.

I agree that this design shows quite some extra information. I've tried not to introduce any new concepts though (page states are all there, color-coded legend, circle icons).

There are 2 main problems with the current design that I've tried to address:

1. the color-coded legend covers possible states inconsistently (`Visible` & `Non-Visible` vs `Modular` without `Non-Modular`) and incompletely (missing `Published` / `Non-Published`):
![screen shot 2017-08-03 at 14 44 11](https://user-images.githubusercontent.com/902958/29212653-fbb04d9a-7e9f-11e7-8a1a-9a4a9d86534e.png)
2. the color-coded icons in the page list show a single (to me arbitrary) aspect of state (e.g. `Modular`) and hide the rest of the state (`Non-Routable`, `Non-Visible`, `Non-Published`):
![screen shot 2017-08-11 at 14 24 42](https://user-images.githubusercontent.com/902958/29212860-ecb7982e-7ea0-11e7-8513-f2662ebb3737.png)

In the current design the user is already forced to look up the color-coded meaning of the icon. I'm not proposing to remove or replace the tooltip that shows on hover. Therefore I think the design I proposed (just a first iteration) makes it possible to read things in the first place, rather than making it harder to read them.

Looking forward to hearing your thoughts!

**Comment by Crolug** [comment]
I find it very useful. The current system is incomplete - tells almost nothing. Imagine you'd have to manage big site with many pages. Can't say it's complex - for me it's simple and efficient - I'd have to remember four colors, which come in two states - it would take me 4-5 glimpses to get used to it.

**Comment by mahagr** [comment]
Admin 1.10 has new implementation with the possibility to see the type from the list page (vertical `...` icon)
