### ISSUE TITLE
Theme overview

### ISSUE THREAD

**Issue by axel-rank** [getgrav/grav-plugin-admin#1208]
if you have 2 themes installed in admin it looks like this:

![image1](https://user-images.githubusercontent.com/12480617/29752588-47f87c0e-8b61-11e7-8d7a-472448178b00.png)

too much space left between.

**Comment by rhukster** [comment]
This is really just an edge-case with flexbox and having 2 items.  The only other real option is not use flexbox at all, and rewrite this with something else.  Higher priority things are grabbing my attention though.  If you wish to submit a PR to address this, i'll gladly consider it.

**Comment by ehllo** [comment]
It should work, if you just change in the class ".card-row" justify and space-between to start(without space between the items) or space-around(evenly better spaced than now). 

`
.card-row {
	justify-content: space-around; /* or use start*/
}
`  

Maybe you should think about removing all the uneeded classes, because it should work across all modern browsers.
