### ISSUE TITLE
Debug bar script added outside of body and html tag - illegal markup

### ISSUE THREAD

**Issue by marktaylor46** [getgrav/grav-plugin-admin#1254]
When you enable debug mode in GRAV the debugbar script is added after the closing html tag - although most browser can cope with this it is technically illegal markup - the script should really be inside of the body tag.

![2017-11-01_15-26-32](https://user-images.githubusercontent.com/11683218/32282506-9d127d98-bf19-11e7-9d6b-9790ae63a9dd.png)

**Comment by rhukster** [comment]
While this sounds like an easy fix, it's a bit complicated because one of the things we track and measure is the render() process which full echos out the contents of the all the templates. So once it's echoed, we can't go back and an inject the debugger output.  I'm not sure that fixing this is worth while because we would lose that valuable metric on how long the render took.

**Comment by rhukster** [comment]
Also this is not intended to be used in production where validation means something, this is for development only.

**Comment by mahagr** [comment]
It's actually possible to include this inside of the document with few tricks. I have some plans to improve rendering of the page in 2.0 and this will become easy to fix once I've made some changes to the logic.

**Comment by marktaylor46** [comment]
Shouldn't we leave the ticket open then so it does not get forgotten?
