### ISSUE TITLE
Admin Tab Toggle no longer works

### ISSUE THREAD

**Issue by sjclark** [getgrav/grav-plugin-admin#1334]
With the new styling the **admin sidebar toggle no longer operates** as the H3 logo element sits on top. Either adjust the h3 styling bounds or add z-index: 1 to the toggle itself.

Grav v1.4.0-rc.1 - Admin v1.7.0-rc.2

![screen shot 2018-02-08 at 4 02 30 pm](https://user-images.githubusercontent.com/4531017/35953472-b412b1ca-0ce9-11e8-84e2-332a3f1783c9.png)

Unrelatedly - the new markdown editor icons are terribly illegible - should really go back to the filled icons.

![screen shot 2018-02-08 at 4 14 24 pm](https://user-images.githubusercontent.com/4531017/35953802-3dbca132-0ceb-11e8-9fdc-ff0cb336e747.png)
vs
![screen shot 2018-02-08 at 4 14 35 pm](https://user-images.githubusercontent.com/4531017/35953812-4148fab2-0ceb-11e8-8e12-a0d1d70c3cdd.png)

**Comment by paulhibbitts** [comment]
I have to agree here re: text and icon legibility in the Admin Refresh - everything else works so well but the new lineawesome icons esp. in toolbar are much harder to see. Might a larger icon size help too?

**Comment by sjclark** [comment]
@paulhibbitts I'm fairly sure the screenshots I put are at actual size - so looks like they have decreased the size. I agree with the larger suggestion too. I think in general the theme redesign is a bit too light & theres not enough visual contrast between things anymore. Finding it hard to use. I would've asumed they would've just put a toggle for light or dark theme.

**Comment by rhukster** [comment]
Fixed the h3 issues, and also I've added the ability to use "Font-Awesome" icons rather than "Line-Awesome".  I personally feel the lighter weight icons are refreshing and look great on retina displays, but if you wish you can toggle them back to the previous bolder style.

Regarding the overall style, there's really no way to please everyone, but I think this lighter style has broader appeal.  Customizable styles are something that is coming.

**Comment by paulhibbitts** [comment]
Awesome @rhukster , thanks for adding a font choice option!
