### ISSUE TITLE
Enhancement: disable user while still enabling admin sessions.

### ISSUE THREAD

**Issue by joachimesque** [getgrav/grav-plugin-admin#1421]
Hi everyone !

This enhancement request is basically the same as issue #29, from 2015.

The use cas is similar : I need an separate cookies for the admin panel, and a way to disable regular visitor cookies. My reason to bring this issue back is related to privacy (and the coming [GDPR](https://en.wikipedia.org/wiki/General_Data_Protection_Regulation)) : I want the ability to not give cookies to visitors, and only have them given to admins.

I guess the only use of these visitor session cookies is to display stats in the dashboard, but I can live without them :)

Thanks!

**Comment by rhukster** [comment]
I've renamed your title, because we have separate sessions already, but what you actually want is NO user sessions, but with admin sessions enabled.

This is probably not a simple one to solve without completely reworking how sessions work.  This is something we're looking to improve in Grav 1.5, so we can revisit it then.

**Comment by joachimesque** [comment]
Thanks for your answer and for adding more precision to the title :)

**Comment by mahagr** [comment]
This one has been fixed for Admin already, but Grav still needs an update to 1.5 (we're going to release beta/RC in few days).
