### ISSUE TITLE
Can't revert changes from template "update" done through Grav admin panel.

### ISSUE THREAD

**Issue by BSA-US** [getgrav/grav-plugin-admin#1492]
Noob here,

Days ago, I vaguely remember hitting “update” in the Grav admin panel as I usually do, and it did an update for my “clean blog" theme, and now it seems all of the CSS changes and other changes I've made have been reverted back to the default settings for the theme.

I can’t see any update history through the admin panel, though, let alone revert anything, and the site isn’t reflecting what’s in my GitHub repo anymore. CSS and all. I've been editing and pushing remotely through GitHub Desktop, and the repo isn't currently being reflected, so it seems things are being overridden somehow through Grav. The webooks are fine for my repo.

Main changes I’m seeing:

• Header text sitting over banner (which I removed before).

• Highlighted text and graphics are now blue instead of #d60000 (red). This was the default color for the theme.

• Our favicon disappeared and reverted to the default Grav one.

• Text on pages is a darkish grey instead of black.

• Banner images are not formatted correctly.

**Comment by rhukster** [comment]
If you made changes directly to the theme, then updating that theme with a new version would copy over those changes you made.  This is because updates are not smart enough to merge any local changes you have made, but there are several recommended ways to make edits without losing them on updates: https://learn.getgrav.org/themes/customization

Also if you have configured the theme by manipulating the YAML in the theme itself, then again, an update would of overridden your edits.  This is because you should not be editing that file, but rather using a copy of it in your `user/config` folder.  Admin plugin does this for you automatically.

long and short of it is, that if you have small minor changes, then Theme inheritance might be a good option.  If you are making larger edits, then we recommend copying a base theme as a new theme.  There's even an option in our `devtools` plugin to make this process easier: https://github.com/getgrav/grav-plugin-devtools
