### ISSUE TITLE
Changing the slug generates a bug

### ISSUE THREAD

**Issue by symac** [getgrav/grav-plugin-admin#15]
When editing a page, then Advanced > checking slug and adding a new slug, then saving, you are redirected to the same page with a message saying that the changes were successfully saved, but the url to the page still contains the previous slug, so instead of being on an edit screen for the current page, you are in fact on a create screen for a new page for the previous slug (don't know if this is clear bug hopefully, replicating the issue you will find easily where the problem is).

**Comment by flaviocopes** [comment]
That field changes the `slug` header (see http://learn.getgrav.org/content/headers#slug). It's just an alias, so the page is accessible both through the original slug and the overridden slug header field.

**Comment by rhukster** [comment]
I can replicate your issue.  it's pretty minor. The change was done correctly. if you go back to the 'pages' you will see the slug is updated correctly.  Also on the frontend it is correctly using the slug override.  

The issue is that when you save and the slug changes, it is not refreshing the URL part.  So it's a just a minor redirecting issue.

**Comment by symac** [comment]
@rhukster you are right it is not a major issue, anyway thanks for fixing it!
