### ISSUE TITLE
Invalid Security Token

### ISSUE THREAD

**Issue by rezacms** [getgrav/grav-plugin-admin#1556]
Dear GRAV team,

we have implemented your GRAV CMS in one of our projects and we have noticed an issue with the Fontmatter in the Expert Mode when inserting content that contain 1000 lines and more.

In that case GRAV says “Invalid Security Token” when we try to save changes in the Normal Mode. Thus changes in that particular entry cannot be changed/saved which is quite uncomfortable since one of our clients cannot edit its affected content. Can you guys lend us a hand here and help us out?  For a sample of the page see attachement please.

Thank you in advance.

Many Greetings from Hamburg 

[sample.zip](https://github.com/getgrav/grav-plugin-admin/files/2675467/sample.zip)

**Comment by rhukster** [comment]
Seems to be a matter of the form failing because it's exhausting PHP resources.  1000 items is really too many to manage in frontmatter, and your blueprint yaml is very nested and quite complex.  Also you are using `pagemediaselect` which makes an ajax call every time it's used.  Overall you should look to another solution for managing this amount of data.  Maybe multiple pages rather than a single page with everythying in it's frontmatter?  Or perhaps flexdirectory plugin?

**Comment by rezacms** [comment]
Hi @rhukster ,

Many thanks for the answer.
We have another problem in this part of the page:

```
.childIds:
  label: sub filter items
  type: array
  value_only: true
```

 The json output looks like this (right):

```
  childIds: [
    "abc",
    "xyz",
  ],
```

  but sometimes after saving -childIds looks like this in our json (not correct):

```
    childIds:{
      "1":"abc" 
      "2":"xyz" 
     }
```

can you help us with that?Thank you in advance.

attachement: Our 
[twig-sample.zip](https://github.com/getgrav/grav-plugin-admin/files/2679447/twig-sample.zip)
Json twig

Many Greetings from Hamburg
