### ISSUE TITLE
All records disappeared after update CMS

### ISSUE THREAD

**Issue by ZelTrad** [getgrav/grav-plugin-admin#1680]
All records disappeared after update CMS v1.6.8 to v1.6.9  =\ The update was automatic.

![1](https://user-images.githubusercontent.com/49678741/57995630-2f7eb800-7ad4-11e9-89a8-4a5dd002e914.png)
![2](https://user-images.githubusercontent.com/49678741/57995633-31e11200-7ad4-11e9-819b-78183149a27f.png)

**Comment by rhukster** [comment]
First Grav doesn't really have automatic updates.  You have to initiate the update yourself. Either in the backend or the frontend. Also updating Grav only updates the 'core' and doesn't touch the `user/` folder at all where your content is contained.  So i'm 100% sure something else is going on.  It's quite hard to tell what is missing because I never saw your site 'before' so just circling an area is not really very useful.  The fact you are still displaying titles means 'something' is there, perhaps you have an CSS issue that means the data is there, but not displaying? Try using your web developer tools in the browser and inspect that area.
