### ISSUE TITLE
Hidden Fields in Grav CMS

### ISSUE THREAD

**Issue by lenaoetting** [getgrav/grav-plugin-admin#1733]
Hi Graph CMS team,

Can you let me know what the best practice is to create forms with hidden fields through GraphCMS? I understand how we can edit form fields – but for tracking/attribution purposes we need for example to store clidkIDs or clientIDs or marketing channel attributions in hidden fields to be able to later do cohort analysis/segmentations in our CRM infrastructure.

How can we add these kinds of hidden fields in Graph CMS, ensure that these forms are displayed?

And secondly: Does Graph CMS offer any built-in functionality to automatically pass values from the current URL or the DOM into hidden fields? I.e. Unbounce as a landing page editor would automatically pass values from URL parameters into hidden fields if the hidden fields were named just like the URL parameter. Here we would also appreciate the best practice on how to achieve this with Graph CMS.

**Comment by rhukster** [comment]
If you are looking for help with "Graph CMS" you have the wrong project.  This is the repo for "Grav CMS", and on top of that this is the "Grav Admin Plugin".  Each plugin has its own repo, so for the form plugin, it's here: https://github.com/getgrav/grav-plugin-form.

Please recreate your issue here.  Thanks.
