### ISSUE TITLE
Requirement Specification: multi language content editing

### ISSUE THREAD

**Issue by cord** [getgrav/grav-plugin-admin#174]
the current approach to edit multiple languages through the admin interface is basically to switch the complete language. This works, but does not support a typical workflow as I would see it. 

Therefor I would like to collect requirements for multi language content editing in this thread.

**Comment by cord** [comment]
## Page editing
it should be easy and fast to switch between language version, so a tabbed interface would be great.

A side-by-side interface would support the translation process.

**Comment by cord** [comment]
## handling content changes

typically there is one leading language, which then is translated. 

There interface should support the case of changes in the leading language, which need to be transferred into the other languages. Somehow it should be visible to the translator which content of the main page was editing "since the last time" the translation was updated. (just think of we would like to offer a translated version of learn.grav.org - somehow the translators should be able to see what has changed)

**Comment by Vivalldi** [comment]
@cord From what I've seen in multi language development it is "better" to use the translations we used in that a human is much more grammatically correct at translations than a computer. I for one would rather have people do translations than a computer.

**Comment by cord** [comment]
@Vivalldi , agree! all above is to support humans to translate content and keep translations updated

**Comment by rhukster** [comment]
Just FYI, some of the items you are suggesting are not really possible with the Grav multilang implementation.  This is because each language is independent from the other languages.  when your in one language mode, Grav doesn't know about the pages from another language.  Basically they work independently almost like 2 independent sets of content. 

So having panes with a default lang showing while editing another language is not really doable without some very hacky stuff going on.

These design decisions were based on a tradeoff between functionality and performance. If we had made all languages available together but somehow segregated in the cache structure, it would of slowed every site down by `n` for each language added.  And as you added more pages, the overhead would grow exponentially.
