### ISSUE TITLE
Cross-Site Scripting (XSS) vulnerability

### ISSUE THREAD

**Issue by JohnMica** [getgrav/grav-plugin-admin#1807]
hi guys it seems that the bootstrap dependency you are using has a potential Cross-Site Scripting (XSS) as per Snyk
 Cross-Site Scripting (XSS)

Vulnerable module: bootstrap
Introduced through: `eonasdan-bootstrap-datetimepicker@4.17.47`
Exploit maturity: No known exploit
Fixed in: `3.4.0, 4.0.0-beta.2`
Detailed paths
Introduced through: `grav-admin@1.0.0 › eonasdan-bootstrap-datetimepicker@4.17.47 › bootstrap@3.3.7`
Remediation: Your dependencies are out of date, otherwise you would be using a newer bootstrap than bootstrap@3.3.7. Try relocking your lockfile or deleting node_modules, reinstalling and running snyk wizard. If the problem persists, one of your dependencies may be bundling outdated modules.

Overview
bootstrap is a popular front-end framework for faster and easier web development.

Affected versions of this package are vulnerable to Cross-Site Scripting (XSS) via the data-target attribute.

just thought I should bring out this in case you haven't noticed yet.

Since the repo is no longer maintained for the datetimepicker plugin as per the Github notes, 
```
This repo is no longer actively monitor or supported. All future work is being done to https://github.com/tempusdominus/bootstrap-3
```
already opened an issue with the `tempusdominus` repository (even though it hasnt been updated in a long time as well)

**Comment by w00fz** [comment]
This really isn't anything to be worried about and this also was kinda beyond my reach because that old bootstrap dependency was in the datepicker dependency so technically until they update that we cannot do much about it other than finding a different module.

However, given that datetimepicker has been unmaintained for a while, I decided to bring it in as part of our JS, remove it as a dependency and so add the bootstrap dependency from our codebase, which allowed me to up it to 3.4.1 and solve the report above.

Thanks.
