### ISSUE TITLE
Hide (modular) page types in Admin automagically

### ISSUE THREAD

**Issue by fosil** [getgrav/grav-plugin-admin#1828]
It would be nice if it was not necessary to enter all types individually, but to set a certain naming convention. E.g. ignore all templates with name starting with underscore - e.g. _templateto_be_ignored.html.twig. 

Ideally with a switch in plugin settings that can enable/disable this feature.

Have you considered something like this?

Thx

**Comment by rhukster** [comment]
Where in the admin are you referring to exactly?

**Comment by mahagr** [comment]
I think he refers the admin plugin settings where you can hide page types. That said, I don't think there is really need for that -- there is an event for plugins which you can hook into and remove the types you don't want to be listed.

**Comment by w00fz** [comment]
I think what @fosil means is to have a way to specify a pattern in the admin setting @mahagr is mentioning.

Right now you have to select all the templates one by one but in the input field if you were to type `_templates_*` as a pattern, it would automatically ignore any template named like that.

I personally do not find this much useful, but I have never found myself needing to hide any template, let alone a multitude of templates based on a pattern.

**Comment by fosil** [comment]
My most common use case is:
I will create websites for customers. Some pages are unique (Homepage, Blog item list, etc.) - in them the customer changes the content, but is not allowed to add another page of the same type. Others, on the other hand, must add (blog post). Since the number of unique ones is usually larger, it would be easier for me (also because of the easy orientation in the template files) to define some naming convention for ignoring in the Admin plugin than to list each one.

**Comment by w00fz** [comment]
This is implemented in 1.10 now. You will be now able to pass regex as values to fine tune what to hide. It adds very little overhead because by default it will always try to match a value to an existing entry but the fallback now is for regexp.

Here is an example for page types:

Imagine i have 2 page types `issue-1234` and `issue-abcd`. You can now set it to `issue-*` and none will display. 
Alternatively you can also decide to only hide the numerical ones, in which case you would specify `issue-\d` (\d = digits) or to only hide the alpha one, you could do `issue-\D` (\D = non digits).

| No Selection  | Wildcard Selection | Digit Selection | Non-digit Selection |
| ------------- | ------------- | ----------- | ---------- |
| <img width="151" alt="Plugin: Admin Panel - Grav 2020-11-21 15-24-37" src="https://user-images.githubusercontent.com/11734/99889833-b783d780-2c0d-11eb-98d1-1ca91879df0c.png">  | <img width="119" alt="Plugin: Admin Panel - Grav 2020-11-21 15-25-31" src="https://user-images.githubusercontent.com/11734/99889850-d8e4c380-2c0d-11eb-956d-7df330d90a1e.png">  | <img width="176" alt="Plugin: Admin Panel - Grav 2020-11-21 15-23-27" src="https://user-images.githubusercontent.com/11734/99889818-8c00ed00-2c0d-11eb-819f-04499cd632ad.png"> | <img width="135" alt="Plugin: Admin Panel - Grav 2020-11-21 15-22-04" src="https://user-images.githubusercontent.com/11734/99889793-712e7880-2c0d-11eb-8961-853267e6be05.png">   |

And the same works for the modules:

| No Selection | Regex Selection |
| ------------- | ------------- |
| <img width="105" alt="Plugin: Admin Panel - Grav 2020-11-21 15-32-41" src="https://user-images.githubusercontent.com/11734/99889929-d171ea00-2c0e-11eb-879d-a6b4f6201090.png"> | <img width="108" alt="Plugin: Admin Panel - Grav 2020-11-21 15-33-36" src="https://user-images.githubusercontent.com/11734/99889946-f1091280-2c0e-11eb-9004-8cc22f510230.png"> |


Hopefully this is what you were looking for!

**Comment by fosil** [comment]
Wow, that's great news for me! And I think not just for me. Thanks!
