### ISSUE TITLE
Admin v1.10.0-rc.7 Very distracting use of red status message with Add Page - any alternatives?

### ISSUE THREAD

**Issue by paulhibbitts** [getgrav/grav-plugin-admin#1848]
When a new page is created in RC7 a message stating that the page is not saved yet appears in red:

<img width="1200" alt="2020-03-06_07-23-57" src="https://user-images.githubusercontent.com/1812771/76097486-a6f6d880-5f7c-11ea-8cf3-24a6e84c2322.png">

This message, combined with the green file location message, is **very** distracting when a new page is created each and every time... are both items needed? Perhaps less distracting alternatives?

Might there be an option to hide these? Could a newly created page be automatically saved (when would one not want to save a newly created page)?

For reference, here is the same state with Grav 1.6.x:
<img width="1200" alt="2020-03-06_07-23-50" src="https://user-images.githubusercontent.com/1812771/76097617-defe1b80-5f7c-11ea-98ea-990377736fb4.png">

Thanks very much,
Paul

**Comment by rhukster** [comment]
How about this:

![Image 2020-03-06 at 10 50 00 AM](https://user-images.githubusercontent.com/1084697/76108690-470e2b00-5f98-11ea-97ad-4f1b02884f50.png)

**Comment by paulhibbitts** [comment]
Thanks for looking at this @rhukster , for sure a HUGE difference with not using Red for that message👍

Re: UI text, do either of these do anything for you?

`[lightbulb icon] This page will not be created until it is first saved.`

`[lightbulb icon] This page will not exist until it is saved.`

I really like your initial use of an icon to help highlight the message type...

**Comment by w00fz** [comment]
I think the choice of red was to purposely attract attention to the warning that the page was not yet saving. In Grav Admin that means things like Page Media won't be available etc.

While I agree that chosen red was extremely bright, I still think red is a better choice for the purpose of the notice, you should be attracted to it and you should save your page to make it go away.

So maybe just a less bright red?

**Comment by rhukster** [comment]
I actually like the slightly dark green.  There are standard colors in the admin.. as the green is always above it in the path notice, it really can't be the same 'note' color.  I think red is a bit scary, but the message is important.  The slightly darker green (secondary color) gives it some contrast without it being overly intimidating.

I like the idea of the lightbulb icon and i've gone with your second text.. short and sweet.

**Comment by OleVik** [comment]
Could we make consistent use informational messages, including colors? Red is for fatal or otherwise obstructive errors, yellow is for warnings, blue is for information, green is for success.

The message "Remember to save your Page" is information, and should be a warning if the user tries to leave the page without saving. "This page does not exist yet!" is inappropriate; the user is clearly creating the page, but they might not want to save and/or publish it yet. It does in fact exist - I am looking at it - but I need to save it (to the filesystem) to store it.

The darker green is close enough to blue, indicating information, but please reconsider the semantics and nomenclature: "Remember to save the Page" or "Remember to save the Page once you're finished editing it" is better than indicating its existence.

If the user tries to navigate away, warn them, and ideally auto-save the draft to localStorage along the way.

**Comment by paulhibbitts** [comment]
When the timing is right, I'd be happy to help out with the effort re: colour blindness considerations, UI icon/text choice etc.

**Comment by mahagr** [comment]
@OleVik This message can appear also when you're creating a new translation. It is there to prevent user accidentally editing the wrong language (like if you should have edited default instead).
