### ISSUE TITLE
Changing a page template causes the other language versions of that page to lose their "content" 

### ISSUE THREAD

**Issue by ptarmic** [getgrav/grav-plugin-admin#1958]
I'm running Grav v1.7.0-rc.17 and admin v1.10.0-rc.17
If I change the "page template" for a page and then switch to another language version of that page the "content" section comes back blank, both the "title" and content fields but also any custom fields on that page. The "Page Media" and other other tabs (options, advanced, etc) are unaffected. The other-language.md file is still in the page folder and still has all the data in it. Switch to/from Normal - Expert mode does not bring through the missing page content.

Also - not sure if this is related / intended but if I then change the page template for this translated page then the .md file is deleted. This doesn't happen with the first language where the original .md file/data is retained.

**Comment by mahagr** [comment]
This one looks like a bug to me.

Changing template is somewhat questionable action to me, mostly because it's not clear what should happen in that case. Should the other languages be updated too or keep using the old template? What happens to the extra fields that get lost? And so on. 

I almost disabled changing the page template in admin, but at some point I decided that it was working, so I left it enabled.

@rhukster What do you think? To me, there are too many undefined things on changing page template. We either need to define the behavior (and create tests on it) or leave the feature disabled.

**Comment by rhukster** [comment]
I think the logic we had in 1.6 was that changing a template was pretty drastic, and it basically ignored anything in the save other than the template change.  Then things that were perhaps no longer valid for the new template were just left in the .md. It should not change the template for all language variations, as it's possible to have language-specific templates.

**Comment by mahagr** [comment]
I just tested this, and it can actually happen the other way, too. For me the edited page lost the contents, every other language is fine.

**Comment by mahagr** [comment]
Fixed in https://github.com/getgrav/grav/commit/b50dbf3ff078ef320bb31477da2189e43671dcc5 (commit message is wrong)
