### ISSUE TITLE
Incorrect position of 'fa fa-chevron-down' icon at some <tr> items in the Plugins page

### ISSUE THREAD

**Issue by Alek6** [getgrav/grav-plugin-admin#1977]
As shown in the image below, the position of the _'fa fa-chevron-down'_ icon is too low and not centered right like the other <tr> item / collapse accordions.

<img width="1162" alt="fa-drop-down icon position ui issue" src="https://user-images.githubusercontent.com/10438241/99706547-82f00e80-2a9b-11eb-86b5-c8bead297c60.png">

**Environment:** localhost, macOS 10.15.5

**Browser:** Google Chrome - v. 86.0.4240.198 (x86_64)

**Problem/UI issue happening:** Recently. Immediately after installing the **_Grav Standard Administration Panel Plugin_**.

**Where:** in the Plugins page.

### Summary of the UI issue and steps in which it occurs:
When the user (Admin) clicks on the collapse accordion item.

**Step 1**
<img width="1194" alt="closed accordion item" src="https://user-images.githubusercontent.com/10438241/99706586-913e2a80-2a9b-11eb-9519-9c7cfafbe77c.png">

**Step 2**
<img width="1194" alt="opened accordion item" src="https://user-images.githubusercontent.com/10438241/99706602-969b7500-2a9b-11eb-8ce6-b367ab70e0da.png">

**Comment by w00fz** [comment]
Hello @Alek6 ,

Thank you for the detailed report, really appreciate it. This issue seems to have been resolved already in 1.10 which is going to be released as stable in the next couple of months.

<img width="54" alt="Plugins | Grav 2020-11-20 09-34-18" src="https://user-images.githubusercontent.com/11734/99831196-93dc6680-2b13-11eb-9192-cd23189f43e7.png">

Thanks!
