### ISSUE TITLE
Unable to read translated pages like default.de.md

### ISSUE THREAD

**Issue by NicoHood** [getgrav/grav-plugin-admin#2007]
Grav 1.6 created some markdown files like `default.de.md`. If I open those pages with the new Grav1.7 and Admin 1.10 the content is empty. `default.md` does not exist.

I also want to note, that Grav 1.7. also creates those (languages prefixed) pages and after saving I am unable to read them via admin plugin. They are still on disk though.

**Comment by newbthenewbd** [comment]
To the best of my knowledge, variants of this were [a known problem since a while](https://github.com/trilbymedia/grav-plugin-flex-objects/issues/47) and are at the very least avoidable by turning off Flex Objects for pages in the Flex Objects plugin's config. (Not without its own consequences - in my limited tests, this seems to cause an error to pop up when moving/reparenting a page... I should probably post a separate issue for that one soon.)

I'm not exactly without fault here, having only informally reported it on the Grav Discord server back in July 2020 and only very recently (again with little paper trail) confirmed that it's indeed still happening, so thanks a lot for taking the time to actually submit an issue. :slightly_smiling_face:

**Comment by NicoHood** [comment]
I could fix that by using:
```yaml
  supported:
   - de
   - ''
```

**Comment by mahagr** [comment]
Yes, supported takes only language codes (I need to prevent empty string from being used).

So you have a single language `de`? I will try to reproduce this.

**Comment by NicoHood** [comment]
Yes, my website only supports `de`. I have markdown files with and without de file ending. The ones with de cannot be parsed by grav admin for some reason.

**Comment by mahagr** [comment]
I've already fixed this bug, as a workaround you can add some random language code (there needs to be 2).

**Comment by mahagr** [comment]
https://github.com/getgrav/grav/issues/3147

**Comment by newbthenewbd** [comment]
On my side, can confirm that the problems are gone with all the latest commits - the one with moving too. :slightly_smiling_face:

Thank You!
