### ISSUE TITLE
Add Page dialogue closes unexpectedly when trying to change Page Template

### ISSUE THREAD

**Issue by amadeusp** [getgrav/grav-plugin-admin#2089]
Problem:
When creating a new page in Grav Admin and trying to select a custom page template, the Add Page dialogue closes unexpectedly. It is therefore not possible to create a new page with a custom page template via the Add Page dialogue. In fact it is possible, but only when opening the Add Page dialogue for a second time.

System configuration:
* Apache 2.4.46 
* PHP 8.0.1
* Grav v1.7.7
* Admin Panel v1.10.6
* Custom page template in custom theme
* Firefox 86.0 (64-bit)

Steps:
1. Go to project.tld/admin and authenticate
2. Go to Pages
3. Click on Add Page
4. In the dialogue set a Page Title
5. In the dialogue try to select your custom template

Observations:
* First, this only happens in Firefox for me. Chrome or Safari do not show the same behavior.
* The Add Page dialogue only closes when the item you are trying to select in the Page Template select is outside of the actual Add Page dialogue (meaning, the Page Template select itself reaches out of the Add Page dialogue).

**Comment by w00fz** [comment]
Since I grew tired of fixing this issue every mont, from now on it won't be possible to click on the overlay and accidentally trigger the close action of the modal. This includes selecting an item outside of the modal boundaries from the dropdown which was the main problem.
There is now a Cancel button that can be clicked for closing the modal or the Escape key which is stil available as an option.

<img width="728" alt="w00fz-2021-03-18_@_16 09 43@2x" src="https://user-images.githubusercontent.com/11734/111709157-5e673180-8804-11eb-8a0d-944194157a19.png">
