### ISSUE TITLE
Insert image in markdown editor in pages doesn't work with plus icon button

### ISSUE THREAD

**Issue by ChristianaHoJo** [getgrav/grav-plugin-admin#2098]
Hi!

I tried to click the plus icon to add a page media to markdown editor but nothing happens. It works only per drag and drop.

![image](https://user-images.githubusercontent.com/71634299/111302107-48fed580-8653-11eb-8d41-d6bb542ea8a1.png)

Do I have to activate the function in any settings or is there an javascript problem in my grav project?

I am looking forward to your answer!

Best regards,
Christiana

**Comment by w00fz** [comment]
Hey @ChristianaHoJo , I just realized I am actually unable to reproduce the issue. I click on the ➕ and it does work as expected.

Are you getting any JS error in console?

**Comment by mahagr** [comment]
@w00fz Did you fix the whole issue?

**Comment by w00fz** [comment]
Only the feature is implemented, as mentioned above I can’t reproduce the clicking on the plus not doing anything.

**Comment by ChristianaHoJo** [comment]
@w00fz there's no error in developer bar error console. I am using chrome and also tried firefox. 
Thank you for your Feedback. Then it seems to be an issue in our project and I will search for it. Drag and Drop is working.

Thank you for including title and alt text!

**Comment by w00fz** [comment]
Now that you mentioned you are not using Flex Pages, this issue might be related to that. I haven't been using a setup without Flex Pages in a long time so this could well be a legitimate issue.

I will try and recreate a local environment with Flex Pages disabled and see if that helps reproducing the ➕ issue.

As a side note, I would suggest you try on a staging environment to enable Flex Pages, it should work pretty well and it has been tested a lot. If your site has many pages this would be a lot more manageable too in the admin, the pages list is more functional and faster to load. Flex Pages is not yet used in frontend so that part won't be affected at all.

**Comment by ChristianaHoJo** [comment]
@w00fz Mostly all pages are modular pages and ww have won plugins that extend admin panel. While updating to grav 1.7.x. I tried enable flex pages but then all custom bluprints from theme for each modular are not shown anymore.

**Comment by ChristianaHoJo** [comment]
I'll give it a try....Do I have to consider anything regarding the modules? Almost all pages are modual pages with modules with their own blueprints.

**Comment by w00fz** [comment]
@ChristianaHoJo Everything should be work just like before. I would definitely try setting up a local environment for testing the upgrade so you don't risk breaking anything on production.

Also, I tried just now inserting an image via the plus button and with Flex Objects disabled, but it seems to still be working as expected for me.

**Comment by w00fz** [comment]
Going to assume this is resolved, please feel free to let us know if it's not and I'll reopen the issue.

**Comment by hughbris** [comment]
Just like to say thank you because I found this issue looking for something else, but it tells me how to do something I hadn't yet worked out. I don't use Admin myself, but for the first time I have a client who has inline images that shouldn't go in a template. Now I can tell that client how to do this :) I realise this technique was in the docs all the time now, too, so feel extra silly. I guess I always overlooked the Admin chapter :/

However, I would prefer `alt` and `title` are drawn from the media metafile if it exists, so I'll make that suggestion on ea64270.
