### ISSUE TITLE
Image Button in Editor Shouldn't Start the http://

### ISSUE THREAD

**Issue by McLaynV** [getgrav/grav-plugin-admin#2127]
I suggest the same change as https://github.com/getgrav/grav-plugin-admin/issues/813 for `image` 
https://github.com/getgrav/grav-plugin-admin/blob/d02f3a12e204708843024ce2ca9623fb6e152646/themes/grav/app/forms/fields/editor/buttons.js#L245 
Another good reason is that HTTPS is getting more common than HTTP.

**Comment by mahagr** [comment]
@w00fz There's no such thing as `image:` URI, which is why there's no need to handle it as a special case.

**Comment by w00fz** [comment]
@mahagr not sure what you mean by `image:`, this is not a special case.

I think @McLaynV suggestion is to just remove the automatic rendered prefix of `http://` when adding an image. I fully agree with this since it was poorly assuming your image URL was going to be remote AND not using SSL.

This is fixed now.

**Comment by McLaynV** [comment]
Hello @w00fz, there is one more occurrence in 
https://raw.githubusercontent.com/getgrav/grav-plugin-admin/develop/themes/grav/js/app.js

**Comment by w00fz** [comment]
@McLaynV i believe that file is a leftover from before my cleanup in Nov 2020. I removed it.
