### ISSUE TITLE
500 error: isUpdatable() at line 296

### ISSUE THREAD

**Issue by khaefeli** [getgrav/grav-plugin-admin#218]
Hi!

When I load the admin/pages/ site, I always get:

    PHP Fatal error:  Call to a member function isUpdatable() on null in /www/user/plugins/admin/admin.php on line 296

I think the problem is, that our Hosting has a Firewill which blocks outgoing connections. So Grav can't check for updates :)

1) I think it should return: "no connection" or something else instead of a 500er internal server error
2) is there a solution to specify a http / curl proxy? :)

Cheers

**Comment by flaviocopes** [comment]
One thing you can try in this case is disable `allow_url_fopen` via php.ini, so Grav uses `curl`, and set the proxy configuration of `curl` through the `http_proxy` & `https_proxy` environment variables: http://stackoverflow.com/questions/7559103/how-to-setup-curl-to-permanently-use-a-proxy

**Comment by mosanger** [comment]
I think the error lies elsewhere. The $gpm object which is being used to call isUpdatable seems empty or at least it's not an object at all.

`PHP Fatal error:  Call to a member function isUpdatable() on a non-object in plugins/admin/admin.php on line 296`

**Comment by Sommerregen** [comment]
@flaviocopes @mosanger FYI I got the same error/same line with **Grav v0.9.45** independent of admin version. Updating Grav to latest **1.0.0-rc.1** solved the problem.

**Comment by rhukster** [comment]
Ah good to know.  @mosanger can you confirm that updating to latest Grav solves the issue?

**Comment by mosanger** [comment]
Unfortunately no, it just moved to another line :/
using 1.0.0-rc.1 with admin-panel 1.0.0-rc.2

**Comment by Sommerregen** [comment]
Oh, hm. I guess it has something to do with line [L43-L147](https://github.com/getgrav/grav/blob/develop/system/src/Grav/Common/GPM/GPM.php#L43-L47) of  `system/src/Grav/Common/GPM/GPM.php`. Somehow fetching updates throws an error, which is silenced in line 46. That's why `$gpm->grav` in [line 297 in admin.php](https://github.com/getgrav/grav-plugin-admin/blob/develop/admin.php#L297) is null and the above method doesn't exist.

My proposal is: instead of silencing the error in `GPM.php` one throws a specific message like "Update failed: Couldn't reach the server" or something similar or pass the "real" error from the update check. Then one can catch the error in `admin.php` and passes the error to the front-end.

This does not solve your issue @mosanger , but gives a more specific error one can deal with. My guess out of the blue is, that your server doesn't support `curl` some way and `fopen` is disabled. This is a very hard restriction, but is worth the effort to double-check, whether one of them for you is at least installed and enabled (see phpinfo).

**Comment by rhukster** [comment]
There have been more checks added since rc.2.  Any improvements in this issue?

**Comment by w00fz** [comment]
This should be definitely fixed. There is now logic in place to determine offline or inability to contact the GPM server.

![pages grav 2015-11-20 21-24-48](https://cloud.githubusercontent.com/assets/11734/11316864/54d6de66-8fcd-11e5-8747-17145937be10.png)

Can you guys confirm with the latest admin version?

**Comment by rhukster** [comment]
Closing due to lack of feedback.  Please reopen if required.
