### ISSUE TITLE
all section titles are always h1

### ISSUE THREAD

**Issue by dani-ooo** [getgrav/grav-plugin-admin#2221]
[according to the documentation](https://learn.getgrav.org/17/forms/forms/fields-available#section-field), the `section` field title has a `title_level` attribute that defaults to `h3`. but the attribute is ignored, and instead, all section titles are always `h1` elements.

https://github.com/getgrav/grav-plugin-admin/blob/e9d36b97a85b9cf8baf4fdc78ad5980592351baf/themes/grav/templates/forms/fields/section/section.html.twig#L7

additionally, `field.underline ?:` is outputting a `1` class when set to true. `field.underline ? '' :` would solve this.

**Comment by w00fz** [comment]
That documentation you linked is meant for the frontend form. That section field in frontend, is actually doing what described as you can see here:

https://github.com/getgrav/grav-plugin-form/blob/develop/templates/forms/fields/section/section.html.twig#L8

In Admin, however, we are forcing h1 however. This is partially due to the inconsistency we have between Admin forms and the form plugin, that we are very well aware of.

Unfortunately this inconsistency is not something we can or are willing to fully address, as we are considering completely rewriting the Admin from scratch a later time.

I also believe you are the first person to ever bring this up to our attention!

Sorry!

**Comment by aricooperdavis** [comment]
Unfortunately this note on `title_level` also appears on the documentation for Blueprint Form Fields: https://learn.getgrav.org/17/forms/blueprints/fields-available#section-field

As such a fix is required, but that fix can be a documentation update. I'll submit a pull request.
