### ISSUE TITLE
Inherited theme appearance in Admin Panel looks "broken"

### ISSUE THREAD

**Issue by paulhibbitts** [getgrav/grav-plugin-admin#223]
When viewing an inherited theme in the Admin Panel, the theme looks "broken" as there is no name shown and as well a missing image (please see attached screenshot).

![grav themes hibbittsdesign org](https://cloud.githubusercontent.com/assets/1812771/10646416/d3af32ae-77e7-11e5-8dd8-b0b46fa100fa.png)

It would be nice to have the required blueprint and screenshot files "inherited" as well, so by default the theme looks as it should in the panel. To further customize it, a user could then decide to add their own blueprint and screenshot files to the inherited theme folder.

Thanks for considering this request.

**Comment by rhukster** [comment]
This is not really a bug, but merely a requirement of the admin.

Even though inherited themes are fully functional with what the docs describe, for them to appear properly in the admin they need **at least a blueprint** file.  That is because the admin uses blueprints to know what everything is and how to render them.

So your inherited theme should include a unique `blueprints.yaml` with appropriate information. Also you probably should include an appropriate thumbnail for your inherited theme too.

**Comment by paulhibbitts** [comment]
Thank Andy. I get what you are saying and that is fine, but I still think this would be a great enhancement in the future (i.e. inherit all theme elements required for proper display in Admin) to help more people get going faster with inherited themes.

**Comment by rhukster** [comment]
I don't think it would make a lot of sense really to inherit a blueprint like that.  It would just be confusing as to which was the parent and which was the child, to the admin it wouldn't be able to tell.
