### ISSUE TITLE
Comment for prematurely locked issue #2229

### ISSUE THREAD

**Issue by hughbris** [getgrav/grav-plugin-admin#2250]
My issue #2229 was closed and locked by @w00fz before I could add comments that the community might benefit from. I have been slow to reply, don't mind it being closed, but the tag 'invalid' seems to be based on a misunderstanding and I don't understand closing it after a week of inactivity at all.

In case it useful o anyone else, my reply to @mahagr is as follows:

> You don't have iconv installed on your system 

I would have expected a very different error if inconv was not installed.

> and there seems to be a plugin that uses a very old version of iconv polyfil (1.6 or older from Oct 2017). Make sure you update the plugins!

I think that was it as far as I recall, or perhaps the first one.

I ended up realising my Dockerfile is built on a flawed base image and refactoring it, which was painful but worthwhile for the better result and for the learning :)

I still think there is a problem with error handling here for a small percentage of users, or the dependencies could be updated. Not sure. I'm no longer one of those users, so meh, will close this.

_At that point, I realised it was already closed, which I had noticed but forgotten, and then noticed it was locked so couldn't comment :(_

Feel free to close this and/or comment now.

**Comment by mahagr** [comment]
I still stand on my comment on the issue. 

```
$str = iconv('UTF-8', 'ASCII//TRANSLIT//IGNORE', $str);
```

The error you had is a bug in iconv polyfill, which I verified by reading the changelogs and the code of the library. Polyfill only activates if iconv isn't installed in PHP and offers a partial replacement for the PHP extension. 

The issue isn't in error handling but (somewhat) badly configured PHP together with an old/unmaintained plugin.

This is why I think it was better that the code just failed instead of silently being ignored and resulting in undefined behavior.

**Comment by w00fz** [comment]
I just want to clarify that: 
1. I never closed and locked that issue, i only closed it. I don’t lock issues in general
2. I didn’t close it prematurely, I closed it after a week of inactivity and because there was a good reply to you. The issue was also marked as invalid.

You are making it sound like I wronged you when all I was doing was probably going through my routine issues cleanup and that issue fell into the “can close now” category. You are free to comment on closed issues as well as open new ones just like I did.

**Comment by hughbris** [comment]
Sorry @w00fz, I did make it sound like that though I hoped it was a misunderstanding, as you explained.

> I never closed and locked that issue, i only closed it. I don’t lock issues in general

A GH UI or browser problem, I suspect. The comment button was disabled after typing in my response. Sorry I assumed the issue had been locked (and that you did it!). I had previously drafted a few points in the comment box and when the tab opened again, I finished it.

> I didn’t close it prematurely, I closed it after a week of inactivity and because there was a good reply to you. The issue was also marked as invalid.

My assumption there was based on past experiences with the team and not feeling like it was quite resolved for me (possibly even a bit butthurt about 'invalid' lol). I have to say I haven't noticed much consistency in issue resolutions.

I apologise, Djamil.

**Comment by hughbris** [comment]
@mahagr  
> This is why I think it was better that the code just failed instead of silently being ignored and resulting in undefined behavior.

Understood and I am persuaded now. Thanks!
