### ISSUE TITLE
Add page form class conflict

### ISSUE THREAD

**Issue by Zoxon** [getgrav/grav-plugin-admin#230]
![2015-10-23 20-58-39](https://cloud.githubusercontent.com/assets/3866196/10696433/a56ae792-79c9-11e5-84e7-e2efebec16e9.png)

Admin Panel  v0.6.2

**Comment by rhukster** [comment]
I'm guessing your running the "blog" plugin? This plugin has issues with the admin plugin because it appears to load frontend CSS files even in the admin.  There is already an issue regarding this:

https://github.com/giansi/grav-plugin-blog/issues/1

If the author doesn't fix soon i'm going to remove it from the GPM until it's sorted because we've had several reports of the same thing.

**Comment by rhukster** [comment]
BTW reopen if this is not the case :)
