### ISSUE TITLE
Shutting down website

### ISSUE THREAD

**Issue by Sharags** [getgrav/grav-plugin-admin#2381]
I would like to shut down or archive our website.  How do I go about doing that?

**Comment by u07** [comment]
There is a plugin named maintenance. It can disable the site temporarily.  https://github.com/getgrav/grav-plugin-maintenance
![image](https://github.com/getgrav/grav-plugin-admin/assets/20968145/1a0a135e-8159-434c-90d4-522f19ef5343)

**Comment by rhukster** [comment]
Didn't see any screenshots, not sure what you mean by "I need to shut off services and obtain the URL in order to activate our new website"

Do you need access to your site but cannot login?  If you have FTP or SSH access to the site you can manually reset the account password.  I suggest asking these questions on Grav's Discord Chat: https://getgrav.org/discord

The Gra Admin Plugin's GitHub issues are for issues regarding bug and problems with the plugin itself. Not for questions about using Grav or issues related to hosting/configuration etc.  Discord is the better medium for getting that kind of help.  Good luck!

**Comment by Sharags** [comment]
Thank you.  I've been trying to access or reset the password but keep getting the messages (screenshots below this time).  We no longer want Grav to host our website.  We are using Wild Apricot for our new website.  Therefore, we no longer need your services.  However, we need the URL to transfer our domain name from Grav to Wild Apricot.  I will try Discord but it is very frustrating how difficult it is to get help on this issue.

[cid:4504aa59-3ae6-40e4-a10d-c6fbd554594b]

[cid:fe6646ef-5cfd-48de-88b6-717380c7045b]


[https://y5t6h9a6.stackpathcdn.com/cc5336b0-eed3-4968-926c-39ca6c9f35b8/-/resize/280x80/img.png]<http://leadershipdekalb.org/>


Shara Sanders
EXECUTIVE DIRECTOR
O (404) 373-2491  M (404) 375-0619
E ***@***.***










________________________________

**Comment by Sharags** [comment]
Thank you for the clarification.  I'll see if I can track down the former website administrator.  Thanks again.


[https://y5t6h9a6.stackpathcdn.com/cc5336b0-eed3-4968-926c-39ca6c9f35b8/-/resize/280x80/img.png]<http://leadershipdekalb.org/>


Shara Sanders
EXECUTIVE DIRECTOR
O (404) 373-2491  M (404) 375-0619
E ***@***.***










________________________________
