### ISSUE TITLE
Button not expanding to match translation

### ISSUE THREAD

**Issue by tillsanders** [getgrav/grav-plugin-admin#252]
Some buttons are not expanding to match a translation that is longer than expected.
See example (German translation, Site editor)

![buttons](https://cloud.githubusercontent.com/assets/1533846/10938848/91f7190a-82fd-11e5-9467-ce83d96abd4f.png)

**Comment by rhukster** [comment]
This really can't be fixed with the current implementation of toggle.  The highlight is a sibling element that has no idea the size of the text.  It's always 50% for 2 items, 33.3% for 3 items etc.  That's why one long text item and one short one throws it.

We'll have to look at finding a replacement toggle that does the same thing but handles different text sizes better.

**Comment by w00fz** [comment]
We found a simple and effective way to have the toggle texts occupy all the same amount of space. This should look better on your end now.

Cheers
