### ISSUE TITLE
Error uploading image files

### ISSUE THREAD

**Issue by MichelePalmieri** [getgrav/grav-plugin-admin#298]
![cattura0](https://cloud.githubusercontent.com/assets/9617683/11361300/f0b83e76-928c-11e5-998d-79a1e2fa78a0.JPG)

![cattura](https://cloud.githubusercontent.com/assets/9617683/11361219/246743ee-928c-11e5-99b6-7be558c97cdd.JPG)

**Comment by flaviocopes** [comment]
I guess you're using the PHP's built-in webserver. Grav is not compatible with it because of its limitations.

**Comment by MichelePalmieri** [comment]
It worked until last version

**Comment by flaviocopes** [comment]
Grav works on PHP's built-in webserver, but some plugins (like the Admin plugin) cannot work on it

**Comment by MichelePalmieri** [comment]
The problem caused by the new plugin Blog
Thank you

**Comment by flaviocopes** [comment]
Ok I'm not sure why that is happening (the Blog plugin is a 3rd part plugin), but usually those errors arise only on the PHP built-in webserver.

**Comment by rhukster** [comment]
BTW, We have removed support for the built in web server because the admin doesn't support it fully (and can't due to limitations in the built-in server itself).  With more and more people using the admin it's just too confusing to say "Grav itself can use the PHP built-in web server", but "admin", "taxonomylist", "simplesearch" and many other plugins wont work.

So, I'm just saying, don't use it. :)
