### ISSUE TITLE
Pipeline feature saves but toggles reset on page refresh

### ISSUE THREAD

**Issue by benblee** [getgrav/grav-plugin-admin#318]
In **Admin -> Configuration**, when switching the caching “css pipeline” and “js pipeline” to **Enabled**, then **Save**, then refresh the page, the toggles are set back to **Disabled**, but the site is still running pipeline.

**Comment by flaviocopes** [comment]
Recreated. Very strange, as the other fields in the same section work fine, with no apparent difference in how they are setup. Debugging.

**Comment by rhukster** [comment]
Strange i'm not seeing this behavior on mine. Seems to save state just fine.

![2015-12-02 at 4 27 pm](https://cloud.githubusercontent.com/assets/1084697/11547488/9248479c-9911-11e5-943f-2968905c44ec.png)

**Comment by rhukster** [comment]
BTW tried on a bone-stock install with latest revs of things and again works fine.  What am I missing?

**Comment by rhukster** [comment]
I know what it is.. even tho the system setting is accurate, the admin is showing the state based on the loaded config.  However, we are overriding the config and disabling the CSS/JS pipeline for the admin plugin specifically.  This is because we don't want to pipeline the admin CSS/JS as we don't care so much about performance and it leads to issues when we update stuff.

However, the form generation doesn't know this and is just seeing this state as disabled.  Not sure how best to fix this.. will have to think on it.
