### ISSUE TITLE
Destination of file upload in a form

### ISSUE THREAD

**Issue by sabrilime** [getgrav/grav-plugin-admin#349]
Hello,

I created a form that contains a file upload field:
       .img_link:
             type: file
            multiple: false
            destination: '@self'
            accept: ['image/gif', 'image/png', 'image/jpg', 'image/jpeg']
            label: Image
            validate:
                  required: false

For destination I tried @self and also a relative path but I always get the same result:
In the md file the value of img_link:  'C:\fakepath\yt.png' and the file didn't get upload

Is there a solution to this ?

**Comment by flaviocopes** [comment]
I'm adding support for file uploads in the admin plugin in these days. Right now the field is meant to be used in the frontend only. The admin form needs a bit of adjustment, and also the save locations. With support to remembering what the file uploaded was (for configuration) and allow deleting it.

**Comment by flaviocopes** [comment]
@sabrilime you created a frontend form, or was this added to a page blueprint for use in the admin?

**Comment by sabrilime** [comment]
@flaviocopes It was added to a page blueprint

**Comment by flaviocopes** [comment]
The "file" field is actually intended to be used in the frontend only, that's where it's best used. 
I added a special "file" field for use in the admin, but for plugins and themes configuration (blueprints).

It's a bit tricky because in frontend you don't need to worry about resetting the value, and deleting the media you uploaded.

Since pages have their own media management already, I added a "pagemediaselect" field, which lists the media files already added to a page folder. You just need to select a file and save, and you're set.

Give it a try, it's in the repository already. Sample usage: https://github.com/getgrav/grav-plugin-admin/commit/ece5d43352989c44d3b35028746c2ceeb4276c23#commitcomment-15080817
