### ISSUE TITLE
onClick not set for buttons with name="task"

### ISSUE THREAD

**Issue by properius** [getgrav/grav-plugin-admin#364]
File: grav-plugin-admin/themes/grav/js/forms/form.js
Line: 6

$(document).on('click', **'button.task'**, function(e) {

has the wrong selector. It should be:

$(document).on('click', "button[name='task']", function(e) {

Without this change all buttons on a form will send task='save' set as default in line 319.

**Comment by w00fz** [comment]
What that on purpose @flaviocopes? https://github.com/getgrav/grav-plugin-admin/commit/a27ee216dd575bfe0a23297ac8ae0383823be1a3

**Comment by flaviocopes** [comment]
Currently the only tasks that are handled within a blueprints form submit in Admin are marked with a `task` class:

`<button class="button task" name="task" value="saveas" lang="{{langCode}}" form="blueprints" type="submit">`

`<button class="task" name="task" value="switchlanguage" lang="{{language}}" redirect="{{context.rawRoute|trim('/')}}" form="blueprints">`

Unless you have a specific need to change it, I don't see a reason to change it, do you have an issue at hand or what is the problem caused by it?

**Comment by properius** [comment]
I see your example uses `class="task"` for the additional buttons. The `Save` button doesn't have this class but all the additional buttons have it. 

I should have copied the `Save As` button instead of the `Save` button :-(

By changing line 6 to `$(document).on('click', "button[name='task']", function(e) {` task buttons would be selected by their attribute and not the class. Just an idea. I will revert back to the default code and add the `task` class to my second button.

Thank you for helping me learn the correct usage of the additional buttons.
