### ISSUE TITLE
Search Function Usability Improvement (Search on Enter/Return)

### ISSUE THREAD

**Issue by SirNovi** [getgrav/grav-plugin-admin#372]
When the focus is on the search field: Enter and Return (and optimally also a click on the loupe icon) should prompt the search. 

As it is right now, you need to input a character. If your search term is already in the field you need to backspace first. This is neither user friendly nor does it follow convention.

**Comment by flaviocopes** [comment]
I don't agree, Google works in this way, the OSX Finder search works in this way, that is already enough "convention" for me.

**Comment by SirNovi** [comment]
That's not really true. 

If you hit up a search result in a google search and go back one page, there is absolutely no need to trigger the search again because all your results are still just there, this is not the case in grav.  

The same goes for the Spotlight Search, if you reopen the search, the results are still there.

**Comment by flaviocopes** [comment]
Ok that's a different thing. When going inside a page, and coming back, the search term is still there, but the pages list not filtered.
So what's needed is, clear the search term or apply the filter on the page load.

**Comment by SirNovi** [comment]
Or, what I think would be an acceptable compromise:  
Put focus on the search field and trigger the search on enter/return.

It happened to me several times already that I had to make changes in multiple -but related- pages. So I went back a page and had to do it like I described in the first post, which is a bit annoying. 

I think, that it is not unlikely that you are going to run several searches in succession. So it would be nice to have the search field already on focus (if possible) and trigger the search on enter as well. 

If you would not want to search for anything you shouldn't have a drawback, if you want to search something, either the same term again or a different one it would be way more convenient than now.

**Comment by w00fz** [comment]
Filters and Search query are now stored in local storage and will be automatically repopulated on load. This means it is preserved even if you refresh the page and not just by using the back button of the browser.

The back button of the browser was just populating the form fields because some browsers (Chrome for instance) try to keep state of how you populated forms, but it isn't reliable cross browser. Now it is with the local storage.

This also implies that pages get automatically re-filtered based on whatever state was stored.

This should meet the request you brought up.

Cheers.
