### ISSUE TITLE
Removing Configuration - System - Collection (jquery) - unable to use Admin Plugin

### ISSUE THREAD

**Issue by sturple** [getgrav/grav-plugin-admin#398]
In the configuration of the admin plugin, I removed the collection jquery.
I soon realized this was required for admin.  When i tried to install it again I couldn't.
It gave me a 0 where the jquery text was suppose to be.
In the user/config.system.yaml file i found 
```yaml
collections:
  - 'system://assets/jquery/jquery-2.1.4.min.js'
```
I then had to change it back to 
```yaml
collections:
  jquery: 'system://assets/jquery/jquery-2.1.4.min.js'
```
Maybe if this file is required in the admin, it shouldn't be a configuration.
Regards,
Shawn

**Comment by flaviocopes** [comment]
It is a configuration option because Admin is a plugin, and it's not required to run a Grav site.
The configuration you see is the Grav System configuration, it's no the configuration of the Admin plugin.

If you change and then restore that config you need to put `jquery` in the first input box, followed by the location of the file. When doing so it's saved as 

```
jquery: 'system://assets/jquery/jquery-2.1.4.min.js'
```

If you omit the first input field, it's saved as

```
- 'system://assets/jquery/jquery-2.1.4.min.js'
```

because there is no key.

**Comment by sturple** [comment]
I did not omit the first input filed i had added, when it saved it it omited the jquery.
The only way i could fix it was manually editinging the system.yaml file.
Also maybe the blueprint for the admin should not show this collection option, because once you remove it from here the admin panel no longer operates as it should.
I believe either way there still is a bug here.
Thanks,
Shawn
