### ISSUE TITLE
Cannot change slug if contains slash

### ISSUE THREAD

**Issue by mariosant** [getgrav/grav-plugin-admin#415]
When I try to change a slug to something like `category/title-of-page` I get a `Validation failed: A slug must contain only lowercase alphanumeric characters and dashes` error message.

This kind of slugs work normally when I add it by hand in the *headers*.

Since this works in Grav, someone would expect to work in admin panel as well.

**Comment by rhukster** [comment]
Slashes are not valid in a slug, the message you are getting on the admin is correct.

Ref: https://en.wikipedia.org/wiki/Semantic_URL#Slug

They work on the frontend because we are not able to have validation when you edit/save a text file.  I could add a message on the front-end throwing an error to help prevent this.

**Comment by mariosant** [comment]
Great! A message at debugger console would be really helpful!

**Comment by rhukster** [comment]
Do you mind adding an issue on the Grav repo so i don't forget? https://github.com/getgrav/grav/issues

**Comment by mariosant** [comment]
Sure, I can do this!
