### ISSUE TITLE
Feature request: Undo button for Markdown editor

### ISSUE THREAD

**Issue by LaravelNick** [getgrav/grav-plugin-admin#420]
The omission of a WYSIWYG editor is a major achilles heel for Grav, especially where clients or (non technical) Admins are concerned, but the inclusion of an Undo button would go some way towards improving a poor user experience within an otherwise excellent Admin section.

**Comment by rhukster** [comment]
One thing to consider, most WYWISG editors are lousy at markdown.  We're probably going to go the Prosemirror route as long as they get some issues sorted.  The other problem is that most editors will strip out custom HTML, so you could lose content if you had custom HTML in there. 

The other alternative is to turn off markdown processing and simply store your content as html.  This however is less than ideal because you will lose many of the advantages of markdown including the page and image linking.  Also it goes against Grav's ideals of keeping complex markup out of the hands of the editor, an firmly in the hands of the designer.  This is where most CMSes fall down today.

In our experience people pick up markdown very quickly and find it much 'safer' than HTML even via a wysiwyg because it's intentionally limited.

**Comment by LaravelNick** [comment]
Hey @rhukster, thanks for your reply. As a developer, I completely understand the reasons behind this decision, and I'm all for keeping everything clean and safe. However, developers are going to be using Grav to build sites for clients with varying degrees of computer literacy, and (much as it pains me to say it), I would bet that clients would much rather use a CMS like WordPress, with a WYSIWYG editor, than have to learn a whole new language (albeit a simple one), just to enable them to maintain their content.

I really wanted to use Grav for a project that I'm about to start, but I just know that the Markdown editor will confuse the heck out of my client and result in dozens of support requests.

Therefore, I'm reluctantly going to have to use WordPress or October CMS, which both have WYSIWYG editors, as that's what clients expect, irrespective of the technical implications.

**Comment by rhukster** [comment]
I understand your point, which is why we are going to provide a WYSIWYG in the pro version, it's just not trivial, or at least has implications that a pure markdown editor doesn't.  Anyway, we'll put a notice in there to make people aware.

**Comment by w00fz** [comment]
This is now implemented :smile: 

![2016-03-03 15_00_13](https://cloud.githubusercontent.com/assets/11734/13512632/bbd06860-e150-11e5-80ae-43c897903789.gif)

**Comment by hyperking** [comment]
what wysiwyg library does Grav use?

**Comment by rhukster** [comment]
It's not a wysiwyg it's a code editor called codemirror.

On Sat, Jun 17, 2017 at 8:02, Derry Livenski <notifications@github.com> wrote:
what wysiwyg library does Grav use?
