### ISSUE TITLE
modular pages, no menu links in hamburger navigation

### ISSUE THREAD

**Issue by schml** [getgrav/grav-plugin-admin#421]
Hi there,

how do i get the horizontal menu from modular pages to the hamburger navigation?
![grav_hamburger_navi](https://cloud.githubusercontent.com/assets/17131140/12900805/79ee7f90-ceb8-11e5-85d5-4f6f0cf0b088.PNG)

greetings, Chris

**Comment by rhukster** [comment]
This is not a bug, those links in the horizontal menu are an **on-page** menu that is generated by the modular sections.  It really makes no sense to have those view in the 'mobile' menu because you are already on that page, just scroll!

However, if you did for some reason want them, you would have to make some edits.

First, you can see how the `modular.html.twig` page overrides the `header_navigation` block to add the **on-page** navigation: https://github.com/getgrav/grav-theme-antimatter/blob/develop/templates/modular.html.twig#L29-L48

You would have to put a block definition around the area where the slidebar nav is: https://github.com/getgrav/grav-theme-antimatter/blob/develop/templates/partials/base.html.twig#L81

And then override this too.

**Comment by schml** [comment]
Hi rhukster,

thanks for your answer and sorry for late reply. I see the usage when it comes to usability an seo.

seo:
For mobile search crawlers, a menu is always a verry good idea to help the crawlers divide the sections on the website. Also in search engine resultpages, for example:
 if someone is searching for "mywebsite contact", if there is a menu, google will list http://www.example.com#contact. Thats a verry importand for relevance and ranking!

Also for usability. Why should a user get a navigation on the desktop version and when he returns on a mobile device there is none. Thats confusing.

regards, Christian

**Comment by flaviocopes** [comment]
That's the implementation of the menu in the Antimatter theme and other themes that follow the same way of doing things. I don't think modular pages sections should go in the menu by default, but everyone has its own needs and you can tweak Grav to do what you want.

Themes in Grav have much more power than themes for other CMS, and you can customize any aspect of the site presentation by customizing the theme http://learn.getgrav.org/themes/customization#theme-inheritance.

In your case, this file provides the menu: https://github.com/getgrav/grav-theme-antimatter/blob/develop/templates/partials/navigation.html.twig

**Comment by rolbr** [comment]
Sorry, I'm late to the party.

@rhukster [provided some insight](https://github.com/getgrav/grav-plugin-admin/issues/421#issuecomment-181600836) on how to modify the templates. I'm going to try this.

Just wanted to chime in and say I'm fully on board with [what @schml said](https://github.com/getgrav/grav-plugin-admin/issues/421#issuecomment-192214441).

There's absolutely no reason to provide navigation on desktop – and then hide the nav on mobile. If anything, you'd need the nav on mobile, since screen size and thus visibility is limited. Having jump marks to quickly navigate the site, even a one-pager, is imperative here!

I'd love a quick toggle à la 'show modular sections in menu'. However, this should be handled the same on desktop and on mobile. Doing it one way on large screens and then totally different on small screens feels broken. Especially on such an important item as navigation.

Thanks for reading 👍🥳

**Comment by haendel-chor** [comment]
Even later ;-)

@rhusker gave some insight with the antimatter theme. How would you do it with the BigPicture theme? There are not the same files and they don't have the same code/logic in them.

It would really be great if someone had an idea how to bring back the hamburger menu on mobile devices which is actuelly hidden by the original theme of HTML5Up.

Thanks in advance!
