### ISSUE TITLE
Frotmatter yaml validation 

### ISSUE THREAD

**Issue by Kasparsu** [getgrav/grav-plugin-admin#426]
Currently it just says something is wrong... not letting ppl know what or where... Implement something like this [validator](http://beautifytools.com/yaml-validator.php)

**Comment by rhukster** [comment]
Actually it's already doing this:

![2016-02-19 at 8 28 am](https://cloud.githubusercontent.com/assets/1084697/13179799/d34f0ea6-d6e2-11e5-92b5-87532ec59136.png)

However, in the admin it would probably be more helpful to put this message into an error notice rather than into the output (as it does on the frontend and admin currently)

**Comment by w00fz** [comment]
The new revamped admin now includes am automatic YAML linter, when you switch to Expert mode.

![2016-03-04 11_50_53](https://cloud.githubusercontent.com/assets/11734/13538436/602c24e0-e1ff-11e5-806f-766912c39a05.gif)
