### ISSUE TITLE
"Page File" in Advanced tab does not work with templates in sub-folder

### ISSUE THREAD

**Issue by jstriedinger** [getgrav/grav-plugin-admin#430]
Hey guys.

So, here is the thing. When using a page with a explicit template, say:
``` 
--- 
template: subfolder/mytemplate
--- 
```
The Page editor does not understand the subfolder. More precisely the **Page File** setting in the **Advanced** tab does not show the template, it just shows template that are not in a subfolder but directly in the templates folder.

**THE PROBLEM**
You can't edit a page via the editor, because when you save it will, automatically, change the template for you because it does not recognize the a template in a subfolder.

Hope I made myself clear.

**Comment by rhukster** [comment]
Here's the deal, we cannot really force a lot of things when people are using files, so you are able to set a  template property on the page with a subfolder, however, this is not intentionally supported.

The general rule of thumb that all templates follow is that a specific page is rendered with a specific template at the root level of the `templates/` directory of the theme/plugin.  Anything that is in a subfolder is considered to be something that is not for an entire page, merely a partial template to be used for something else.

We generally put our partials in a `partials/` folder, but this is just naming convention.  The only exception to this rule is `modular/` templates, but these are a special case because they are used to render a modular sub page, into the parent modular page, which will by default use `/modular.html.twig` to render itself.

So the issue is your trying to configure Grav to render a page with a template in a subfolder.  The field in the admin is only scanning for root-level templates to be available in the dropdown to choose from, so the value you set is lost.

I feel the solution to this problem is to ensure your templates for 'pages' are at the root level, and not in subfolders.

Any other solution, like scanning subfolders, will just mean potential issues where people have twig templates in subfolders that are not intended to be for page rendering.  Also there is the performance issue that comes with recursively scanning folders (even if its only 1 extra level).

**Comment by brettdewoody** [comment]
I believe I ran into this issue as well. Here's my setup:

* themes/
  * theme-directory/
    * templates/
      * modular/
        * menu.html.twig
        * intro.html.twig
        * bio.html.twig
      * partials/
        * base.html.twig
        * footer.html.twg
      * module.html.twig
      * about.html.twig
* pages
  * _footer
    * footer.md
  * 01.home
    * ...
  * 02.about
    * ...

If I go to edit the `Footer` page in the admin and click the Advanced tab, the only options the Page File dropdown contains are `bio`, `intro` and `menu`. 

I attempted to move `footer.html.twig` into the root directory (`templates`) but was still not an option in the Page File dropdown. Only after moving it into the `modular` directory was it available in the Page File dropdown. 

If I'm reading your comment above correctly it should have worked to move `footer.html.twig` to the root `templates` directory correct?

**Comment by flaviocopes** [comment]
Your issue is different. The OP problem was he was setting a theme based on a subfolder structure, which is not intended to work.

To solve your case I'd not use a footer.md page, but

- include the footer from the base twig
- in the footer twig, include the footer page, by adding `{{ page.find("/_footer").content }}`
