### ISSUE TITLE
Admin shows default template in template listing 

### ISSUE THREAD

**Issue by Kasparsu** [getgrav/grav-plugin-admin#447]
Even if current theme does't have a template "default" it's still shown .. And it can cause some problems for less advanced users because the make a page and then it doesn't work.

**Comment by flaviocopes** [comment]
@rhukster should this taken into consideration? If the theme does not provide a default twig implementation, hide the default page type when creating a new page / editing a page?

**Comment by rhukster** [comment]
This logic to add a 'default' template is actually added.  I'm just trying to remember why I did that, because there was a legitimate reason.

**Comment by Kasparsu** [comment]
@rhukster So if template doesn't have blueprint it has default blueprint as far as I understand. And if has blueprint it can extend default one. But as far as I understand showing it as an option to select is not useful unless there actually is default template in theme.

**Comment by mahagr** [comment]
The reason why default is shown in the list is because of how the implementation works. Types class has to have default type listed or it won't be able to extend other types with default. Also default type is used whenever new type doesn't have its own blueprints. SnipCart plugin is an example of this.

Not sure if I agree on the logic myself, but after staring at the code for several days, that is how it works. Types are primary defined by their blueprints, not by their template files. That makes default type a mandatory type -- you just cannot ignore it in theme.

**Comment by Kasparsu** [comment]
I can and I have .. by hardcoding this into `$types = self::getTypes();
        $types2 = $types->pageSelect();
        unset($types2['default']);` into pages/types() the problem in this case is that it ignores "default" template even if it exist in the theme...
