### ISSUE TITLE
Add 'Save for Review' (Save Draft?) functionality for non-super admin users.

### ISSUE THREAD

**Issue by simonlayfield** [getgrav/grav-plugin-admin#485]
I really, REALLY like what I'm seeing from both Grav and in particular from this plugin because I think it perfectly delivers on on the simplicity needed for both developers and clients on several of my small projects without compromising on features.

Saying that, a recent project required that content editors (non-super) are able to make changes to content but not actually publish (this would be actioned by a super admin).

![sfr](https://cloud.githubusercontent.com/assets/2576361/14376116/1fea44a4-fdaa-11e5-88ec-138ca6f217ab.png)

I actually think this is a pretty useful feature for content creators who may not necessarily want to publish changes straight away, and in this case from a permissions perspective it adds a rudimentary review process for teams.

Is there a plan to include this in the future by any chance?

**Comment by rhukster** [comment]
This is not really something we have planned for the regular admin.  You could tell your content creators to always create content with with `published: false`.  This would effectively let them create content, but wouldn't be live until you set published to true.

I know this is not ideal, but this is some more advanced publishing workflow that really is something that 99% of users would never use.

That said, it might be something that we add to the Pro version of the admin plugin.

**Comment by simonlayfield** [comment]
Thanks for the response! Sure, I hear you, and it seems pretty reasonable that it's not on your roadmap if you see it as being something 99% of users would never use.

Your suggestion definitely works for **new** content, for sure. However, when maintaining existing site content there would be no way to save edits to a page without re-publishing or unpublishing - and unfortunately saving page changes as a draft (even regardless of user permissions) is crucial for our team working across a business with multiple stakeholders responsible for the content on each page, and thus puts me in the 1% of people who see it as a dealbreaker as far as choice of CMS goes (in this particular case).

Awesome work, though. I'm definitely sold on Grav and will definitely be using it for other things.

**Comment by a1studmuffin** [comment]
Just throwing in my 2c on this issue even though it's closed, I agree with Simon that it would be very useful having the ability to edit an existing page's content in some kind of draft form before making the changes live.

I would have thought this workflow would be used by a lot more than 1% of content creators, as it's very natural once a site is live to need to make significant edits/overhauls of pages every now and then. It's nice to be able to log into the site, work on a draft for a while, then save and close the site (but not publishing the changes yet). Having a fully rendered preview of the draft is also very useful, as the markdown editor doesn't always show what the final page will look like (since it depends on the template in use). WordPress has the nicest flow for this that I've seen so far, where once a page has been published, you can continually redraft and edit as much as you like, but it only goes live when you actively re-publish it. It also offers the ability to see a fully rendered preview of the draft content.

The only workaround I can think of is creating a temporary page for additional drafts that's unpublished, but that's a bit of a cludge for content creators. 

Anyway, I don't think this post warrants much more discussion as it sounds like rhukster agrees this would be a good idea for the Pro version, just wanted to chime in and give a +1 for this functionality, I've been hoping for it for a while. Cheers :)
