### ISSUE TITLE
Number automatically added to foldername on save

### ISSUE THREAD

**Issue by K232** [getgrav/grav-plugin-admin#50]
Within /user/pages/01.blog I have some folders like 'itemA', 'itemB', 'itemC' etc. So I don't use any numbers there. When I use the admin panel and update an existing page, numbers are automatically added at the beginning, e.g. '01.itemA'. I've cleared the number in field 'Ordering' before save but it does not change anything, '01.' is still added to the folder name.

**Comment by rhukster** [comment]
The admin plugin will automatically add numbers and set an order for **visible** pages.  This is how it keeps track of where the pages should be.  

However, it should not add numbers to **non-visible** pages.  

By default Grav treats pages with numbers already as **visible** and pages without numbers as **non-visible**.  You might be overriding this by setting `visible:` in your page header though.  It really depends on how your page is set up.

**Comment by K232** [comment]
So when I use the admin panel it would be better to use numbers, right? What if I specify to sort by date ascending. Would this overwrite the number sorting? I don't have a problem with using the numbers as indexes as long as the sort-definition would have a higher priority than the number used for the folder.

**Comment by rhukster** [comment]
The "visibility" of a page really just means if it should be visible in the menu.  The numbers are just a simple way to order these things.  

For blog posts for example, you would not use numbers, because generally speaking you really don't want your blog posts in your menu, only the top level "blog" page.  You can then order the blog via the headers of the blog page.

As long as you don't try to manually order things in the admin, you shouldn't get the admin adding numbers.

Hope that makes sense.

**Comment by rhukster** [comment]
This has been reworked and should be fixed once and for all in the latest develop branch
