### ISSUE TITLE
Page count includes underscore pages (e.g. modular pages)

### ISSUE THREAD

**Issue by suntrop** [getgrav/grav-plugin-admin#541]
Although I am new to GRAV, I have read pages starting with an underscore aren't real pages. But they are taken into account for the page count in the sidebar.

Count says 29 pages … but I have 5 pages with modular pages and some child pages starting with an underscore as well.

**Comment by rhukster** [comment]
Actually Modular pages are pages within Grav, they are just rendered slightly differently.  The count reflects this.  We are planning on modifying the modular page creation process so that it is much more integrated into a single page.  At this point, we'll modify the page count to reflect this change in UI.
