### ISSUE TITLE
Language strings not displayed in the selected language

### ISSUE THREAD

**Issue by Quy** [getgrav/grav-plugin-admin#552]
Spanish is the selected language, however, the following are displayed in English:
`You have been successfully logged in`

Under `Latest Page Updates` for the nice time `6 days ago`.

DEFAULT_DATE_FORMAT_PLACEHOLDER

**Comment by MATsxm** [comment]
about the `DEFAULT_DATE_FORMAT_PLACEHOLDER` and if I understand well, I would say it is because it has been translated just 9 days ago https://crowdin.com/translate/grav-admin/2/en-es#q=DEFAULT_DATE_FORMAT_PLACEHOLDER then it should be ok for the next release.

**Comment by Quy** [comment]
It is there in beta2:
`DEFAULT_DATE_FORMAT_PLACEHOLDER: Adivinar automáticamente si está en blanco`

**Comment by rhukster** [comment]
Regarding `DEFAULT_DATE_FORMAT_PLACEHOLDER`: I'm pretty sure in the 1.1 beta even tho this placeholder is defined it's no longer used. That's because the Utils::dateFormats() method always provides a value, where as before we had an empty value (where the placeholder shows).

So not sure where you are actually seeing this value displayed?

**Comment by Quy** [comment]
Under `Page date format` for `Guess automatically`..

**Comment by rhukster** [comment]
Ok i've fixed that via the Form plugin, will be avaiable soon.

Also login/logout messages are fixed too.

**Comment by rhukster** [comment]
Ok nicetime also fixed.. should be good to go now.
