### ISSUE TITLE
DateTime::__construct(): Failed to parse time string

### ISSUE THREAD

**Issue by Quy** [getgrav/grav-plugin-admin#564]
In Expert mode, I entered an American date but using `-` instead of `/` and got this error:
`DateTime::__construct(): Failed to parse time string (05-24-2016 08:00) at position 0 (0): Unexpected character`

Can this be gracefully handled?

On a related note, would it be possible to use American date format with the date/time picker?

**Comment by rhukster** [comment]
As mentioned in the docs here: https://learn.getgrav.org/content/headers#date the `/` denotes US format and the `-` denotes european format.  This is because Grav uses the `strtotime()` PHP function: http://php.net/manual/en/function.strtotime.php

You can however provide a custom format in the system.yaml if you would prefer to use that (`pages: dateformat: default: `). 

Regarding the admin picker, please create an issue specifically about that.  

Cheers!

**Comment by rhukster** [comment]
![edit future post grav 2016-05-05 10-28-34](https://cloud.githubusercontent.com/assets/1084697/15049561/22b15274-12ac-11e6-9aa0-e4de165ca98e.png)

BTW added a little nicer error handling
