### ISSUE TITLE
Top green bar disappears after virtual keyboard displays on iPad

### ISSUE THREAD

**Issue by Quy** [getgrav/grav-plugin-admin#582]
To reproduce:
* Go to `Account` page
* Scroll down half way
* Click on `Groups` field to bring up virtual keyboard
* Dismiss keyboard

The green top bar disappears. You have to swipe down several times to refresh the screen to display the top green bar again.

**Comment by rhukster** [comment]
Can't replicate in the iOS iPad simulator.  Will have to try again later with a real one.

**Comment by commodoor** [comment]
I tested this also on mu iPad, when you do the steps described above it looks like the green bar disappears but when you scroll to the top page it shows again. Sometimes you need to scroll two times to show up correctly again.

**Comment by rhukster** [comment]
If that's true then it's just a rendering issue.  Those are very hard (read often impossible) to resolve because it's actually a bug in the browser.  We may be able to find a hackish workaround with a great deal of trial and error, but then again, an update could fix it too.

I really have more important things to be working on, but if someone else wants to try to fix it, i'de gladly accept a PR! :)
