### ISSUE TITLE
Display available themes/plugins in descending chronological order

### ISSUE THREAD

**Issue by Quy** [getgrav/grav-plugin-admin#583]
Currently available themes/plugins are displayed in alpha order. It would be nice to have an option to display in descending chronological order to see recent additions.

**Comment by w00fz** [comment]
Loved this idea so much I took it a little further than what you originally suggested.

Note that at this point there is no persistent state, that would involve cookies in order to restore it on load and I want to first discuss it with the team. I personally think persistent state for this is not really needed.


![jun-27-2016 18-53-20](https://cloud.githubusercontent.com/assets/11734/16401316/96893c8c-3c98-11e6-91b3-4b7092ab3348.gif)

**Comment by Quy** [comment]
This is awesome!!! 

`Release Date` doesn't sort under `Installed Plugins` and `Installed Themes`.

**Comment by w00fz** [comment]
I fixed this now, the issue is that once a plugin/theme is installed, we lose the informations about the repository which is the only location where we know the release date.
I am now making a request to the GPM repository to retrieve that information when sorting by date, the only gotcha is that in case the repository has expired cache and is up to refresh, sorting by date would trigger a re-fetch of the repository. Not as critical since it would happen no matter what at some point, just an heads up.

**Comment by Quy** [comment]
`Release Date` appears to not be sorting under Installed Themes.

**Comment by flaviocopes** [comment]
Fixed

**Comment by Quy** [comment]
In Spanish, `Updates Available` expands to 2 lines due to the narrow width of the select dropdown.
