### ISSUE TITLE
Select menu invokes keyboard on iPad

### ISSUE THREAD

**Issue by Quy** [getgrav/grav-plugin-admin#587]
On an iPad, when a select dropdown has focus, the virtual keyboard appears. I understand its purpose to narrow the selections with the desired keystrokes. However, usability wise it is clunky. Many times the dropdown is blocked by the keyboard. You have to scroll the page up to see dropdown items. Can the virtual keyboard be suppressed?

**Comment by w00fz** [comment]
What you are describing is the behavior of Selectize, the only way to get rid of it is by using regular selects rather than Selectize.
In Gantry, which also uses Selectize, we use both types, regular select when there aren't many items, Selectize when there are plenty and where filtering is more UI friendly. The same logic could be applied in Grav admin but to be entirely honest I think this comes down to personal preference. I, for example, prefer to start typing and filter down a list on a touch screen, rather than using the scrolling wheel.

**Comment by Quy** [comment]
OK. I will have to remember to move the select to the top before clicking on it so the keyboard doesn't block it.
