### ISSUE TITLE
When overriding something in page, `process` is auto-enabled

### ISSUE THREAD

**Issue by rhukster** [getgrav/grav-plugin-admin#646]
I checked `slug` and provided a custom slug, on save, i found `process` was checked with Twig checked. Unchecking and re-saving has no effect.

**Comment by flaviocopes** [comment]
On it

**Comment by flaviocopes** [comment]
@w00fz even when the toggleable is unchecked, I still see it sent to the controller:

![screen shot 2016-06-07 at 11 27 57](https://cloud.githubusercontent.com/assets/11783388/15852841/f136f1e8-2ca2-11e6-8ba5-51e031c5613f.png)

```
  "header" => array:7 [
    "title" => "Test"
    "body_classes" => ""
    "slug" => "xxxx"
    "order_by" => ""
    "order_manual" => ""
    "process" => array:1 [
      "twig" => "0"
    ]
  ]
```

is this expected, or should it be not sent in the request instead?

**Comment by w00fz** [comment]
The checkbox always sending in a value, checked and unchecked, is on purpose because of the issue we had with #616 (636bd15). However the toggleables should still be respected, and in the example above it shouldn't be sent, I'm going to look at it, I think I'm just not checking if they are disabled or not.

**Comment by flaviocopes** [comment]
👍
