### ISSUE TITLE
Drop Files onto the complete Page

### ISSUE THREAD

**Issue by MaZderMind** [getgrav/grav-plugin-admin#651]
When dropping Files onto a Page in the Grav Admin-Panel the Drop-Area is actually pretty small.
I often drop Images onto the Markdown-Editor, which results in a big mess :-)
![bildschirmfoto vom 2016-06-05 18-57-16](https://cloud.githubusercontent.com/assets/142237/15806914/6f9a94b8-2b4f-11e6-92f6-b11c23904ad4.png)
![bildschirmfoto vom 2016-06-05 18-57-49](https://cloud.githubusercontent.com/assets/142237/15806915/6f9ba678-2b4f-11e6-90e9-4eb545d63309.png)

I'd suggest to make the Drop-Area bigger, if possible the whole viewport or at least covering the Editor-Window, like Github does it:
![bildschirmfoto vom 2016-06-05 18-59-21](https://cloud.githubusercontent.com/assets/142237/15806944/d5653b36-2b4f-11e6-8915-eb7406a9138a.png)

**Comment by rhukster** [comment]
Not sure how feasible this is. i'll leave this for for @w00fz

**Comment by MaZderMind** [comment]
@rhukster sure, consider it an idea from someone coming from "the outside" and not as used to the ui as you might be. After some time one will surely become accustomed to it.

**Comment by w00fz** [comment]
The way I implemented it is so that when you drag & drop a text file, such as `.md`, from desktop into the editor, the editor opens and puts the content of the file into the editor (try drag and dropping an md into the editor).

This is different than drag and dropping an attachment such as an image or a zip file, which means we kind of have 2 dropzones.

If the editor dropzone is not as used then we could just make the whole viewport a dropzone for attachments, and text files would need to be locally openend and copy/pasted manually into the editor.
Really it's a matter of preference.

To do it ala github, where drag and drop starts a background upload and occupies the cursor location, would be very nice, but maybe should be reserved for the PRO version because it's not as trivial as it sounds.
