### ISSUE TITLE
`routable: false` not showing but present in `frontmatter.yaml`

### ISSUE THREAD

**Issue by Sogl** [getgrav/grav-plugin-admin#668]
Hello!

Today I found a small bug. If we have this line in `frontmatter.yaml`:
```
routable: false
```

admin panel still shows it as routable:
![image](https://cloud.githubusercontent.com/assets/7556290/16180529/57e5e7de-36d3-11e6-909a-d39b5245307a.png)

And with access to `/places` I see 404 error as it should be.

I think some other options also need to check.

**Comment by flaviocopes** [comment]
This is on purpose. The values of frontmatter.yaml are not loaded in Admin.

**Comment by flaviocopes** [comment]
The Admin workflow does not take the frontmatter.yaml in consideration. This can be discussed and improved of course. It's currently this way because when loading its values and merging them with the page header, then they will be stored in the page once you save it.

**Comment by rhukster** [comment]
I decided it would only complicate things to take `frontmatter.yaml` into consideration in the admin.  It would appear settings were set for the page, which upon inspecting the page were not valid for that page.  Alternatively, it would see the changes and set the values accordingly in the admin, but then upon saving, would save those values to the page rather than to frontmatter.yaml.

it all gets very complicated knowing where those page settings should be saved and where they shouldn't.  I think that `frontmatter.yaml` is an advanced feature and is best left out of the admin entirely as we want to keep the admin 'clean' and as 'simple' as possible.
