### ISSUE TITLE
Blueprints not recognising names with snake case

### ISSUE THREAD

**Issue by Kristjan-Reinsberg** [getgrav/grav-plugin-admin#700]
For example, this will not work:
....
type: select
'@data-options': '\Grav\Theme\myTheme_ee::menuicons' 
....
Started working when i changed my theme name+theme main class to "myThemeee"

**Comment by flaviocopes** [comment]
I can confirm this is the case, replicated.

**Comment by mahagr** [comment]
This is handled in `Grav\Common\Data\Blueprint::dynamicData()` function. The function should not break when using underscores. It shouldn't be psr-4 either, but I do know that psr-0 converts underscores to directory separators.

**Comment by flaviocopes** [comment]
Yep thanks for the pointer @mahagr, that's the reason why it's not working. 

I tested a bit, as per http://www.php-fig.org/psr/psr-0/ it tries loading `user/themes/mytheme/ee.php` (to match your structure above) but also in this case it's not working because being called statically there is nowhere you can load that class in the theme constructor. 

If I load that class manually into another plugin (Admin plugin for example), simply by doing a manual require_once, then it works.

So @Kristjan-Reinsberg , it's not going to work as you expect. Don't use underscores in your classes.
