### ISSUE TITLE
Block admin users from statistics

### ISSUE THREAD

**Issue by gxjansen** [getgrav/grav-plugin-admin#714]
Imho it doesn't make sense to include admin users in the user statistics shown in the dashboard, so would it be possible to mark someone as an admin as soon someone logs in and block them from counting as a visitor?

**Comment by rhukster** [comment]
The stats don't count 'admin views' towards the daily activity.  But it would count admins logged in to the frontend.  It's possible to add logic to not count a user if they are logged in and an admin, but then that's going to need a setting because some people might want to count that, and as that's current behavior would need to be the default action.  Not sure this is worth it considering these stats are really just a rough/general count.

We're planning on breaking these out into their own plugin and adding more functionality. I think at that point it makes sense to add functionality like this.  Cheers.
