### ISSUE TITLE
Not possible to select text double clicking in form field of type list

### ISSUE THREAD

**Issue by wsanter** [getgrav/grav-plugin-admin#724]
Not possible to select text double clicking in form field of type list, or with mouse down move.
![admin](https://cloud.githubusercontent.com/assets/1304598/17307652/80dfdd64-5836-11e6-9aae-9368aa67a993.gif)

**Comment by w00fz** [comment]
Which browser is that? Seems fine for me in Chrome

**Comment by wsanter** [comment]
The problem is with Firefox 47.0.1 osx.
Safari 9.1.2 is ok.

**Comment by rhukster** [comment]
I'm able to double/triple click in chrome, but i cannot drag to select text.

**Comment by w00fz** [comment]
I fixed this by reworking the UI so we won't have this issue anymore, since it's not the first time i see this.

![drag handle](https://cloud.githubusercontent.com/assets/11734/17313255/d8a7e230-580e-11e6-9ba8-85100476f2a3.png)

Now to reorder a list item you will have to use the left drag handle, and won't be able to do it by dragging from anywhere within the list item itself.
Although that was easier, it certainly brought in some issues like the one you described above.

Besides, the old drag handle that was on the top right (replaced now by the collapse/expand icons) was really doing nothing.

I think it's better this way!

**Comment by wsanter** [comment]
Hi woofz,
this was quick, thank you.

Only one thing, i am not sure whether the bar icon at first glance is recognizable as a drag handle. Maybe a tooltip could be useful. But this is a nonissue.
