### ISSUE TITLE
[Feature] Upload <-> Backup

### ISSUE THREAD

**Issue by Swader** [getgrav/grav-plugin-admin#731]
Would be nice to have the ability to upload a backup file in the UI, in order to restore the site to its backed up state.

**Comment by zcmyworld** [comment]
Is there any ways to restore a backup file now?In the UI or in command etc.

**Comment by rhukster** [comment]
A backup is just a zip file.  As if you had just zipped up the folder yourself, with some few folders ignored (cache etc).  So to restore, just unzip it.

**Comment by HenroRitchie** [comment]
How do I restore it if I don't have access to the CLI nor a file/browser explorer?

**Comment by rhukster** [comment]
Do you have access to a browser based file manager such as in cpanel? Else you could probably do it manually via ftp but that really is not super reliable.

**Comment by Romarain** [comment]
@rhukster I support @HenroRitchie on the idea of a feature integration of a restore function.
I think that we don't take into account the client's point of view : the great advantage of a CMS is to use embeded functions, like creating a backup by pressing a button. So, restoring a backup should be as easy. 

If not, it implies the action of the developers to restore a backup.

**Comment by mahagr** [comment]
Though many times the site is broken and the button does not work. :)

**Comment by rhukster** [comment]
Maybe a small file that can be uploaded that does the work. Not needing a running grav.

**Comment by HenroRitchie** [comment]
From my side, I require a method to move a site from one installation to the other. The site is not complex and contains mostly static files and images. So if I run a backup and restore grav should be able to take all the static pages and images, compress them into a zip file. On the new site I should be able to load the zip, extract and the site should be running again.

The problem is if I used plugins which is not available in the new installation. 

One of the other programs I use (Node-Red) splits this process into three parts. The core itself cannot be transferred from one site to the other, and in my case, this is not required. The Node-Red nodes, in Grav's case the plugins, are also not transferred from one site to the other. Only the content of the site is transferred. However, if I transfer a site which uses a certain plugin and it is no longer available on the new site Node-Red alerts me to this issue and still import the rest of the content. Everything will be the same, except the parts of the site which uses the plugin which is not available.

Functionality like this would definitely help. I am not looking a single restore all solution.

**Comment by jonata** [comment]
Maybe you could just update the "Direct install" functionality to recognize the backup zip file content and copy the files accordingly.

**Comment by bstn-chmpns** [comment]
I was looking all over GRAV for that "re-install" button today. I did upload my backup.zip in the "Direct Install" panel, thinking it was made for it... But no. 
It makes a hard life to users like me, discovering self hosting and in need of easy tools like yunohost and stuff...

**Comment by apphead** [comment]
Why is this ticket closed? Is there now an option to restore a backup from the Admin / GUI or are we supposed to unzip everything manually?
grav is just an amazing system. Frankly, I am surprised that this feature is not implemented yet. Or is it?
