### ISSUE TITLE
Editing Page media information via admin interface 

### ISSUE THREAD

**Issue by dimayakovlev** [getgrav/grav-plugin-admin#76]
I remember what @rhukster said about file managment feature.

But Page media really needed ability to edit media information via admin interface (image tiltes, descriptions, etc).

**Comment by rhukster** [comment]
This is a pretty advanced and specialized feature.  It does seem like a prime candidate for the pro version of the admin.

**Comment by ritchiedalto** [comment]
I would love to see this too, and I'd easily pay for it, Grav is officially part of my professional life now. I was thinking, just as you can hover on an image attached to a page (in the page editor) couldn't there be an option for "Image Info" right next to "insert" and "delete"? A user could then edit a list of basic fields for an image, such as title, alt text, long description/caption. And possibly create new fields on the fly. Obviously these are stored on the back end in the image.ext.yaml file/header.

I'm setting up many small modular templates that my clients can use to build their own pages within the layout I design for them. Often enough, so that they dont have to insert image code (![ ]) into their page text, I have a template that simply pulls the image attached to the module/page and puts it exactly where it needs to be in that sub-section of the layout. However this does not afford me a way to add meta data for an image from a template, the most important being alt-text for accessibility concerns.

I've been experimenting with various tech levels of users, and they are all VERY uncomfortable editing a page in expert mode and adding yaml header info. My goals here are to not just design sites for them, but design a very custom system for maintaining their own site with templates relevant to them that handle most of the work, and Grav is near perfect for this!

**Comment by flaviocopes** [comment]
This will be in Admin Pro, a full-page media manager with alt text and any other media metadata you might want to have, as defined in an editable blueprint.

**Comment by flaviocopes** [comment]
I mean, it's already in Admin Pro, just needs to be released :-)

**Comment by tadeo** [comment]
Hi everyone, any new about this? Editing images metadata through the admin is a must have in terms of accesibility, etc.
