### ISSUE TITLE
Admin errors when changing param_sep to custom value

### ISSUE THREAD

**Issue by JeffStarr** [getgrav/grav-plugin-admin#774]
The default value ( `:` ) of `param_sep` is a reserved character according to RFC spec ([more info](https://perishablepress.com/stop-using-unsafe-characters-in-urls/)). Fortunately Grav provides a way to change the default value via `user/config/system.yaml`. 

Unfortunately, doing so results in a 404 for the admin area (if using a custom admin location via the admin plugin settings: "Administrator path"). Or, if not using a custom admin location, changing the value of `param_sep` results in the following errors:

- login page is 404
- admin displays "Invalid Security Token" error
- broken News Feed on the dashboard

Possibly other errors, etc.

**Comment by flaviocopes** [comment]
As replied in the other issue, `:`, along with `?` and `&` and the others, is reserved for this exact purpose we're using it for.

I've checked to see the issue you had when switching param_sep (or changing the admin route, not sure how it's related to that), but I have no issues at all. We never (unless by mistake) use that parameter hardcoded, and I have not found any issue.

I have changed it to `;`, the other suggested separator. What did you change it to?

**Comment by JeffStarr** [comment]
Speaking with Andy Miller @rhukster on Gitter, he said "you can change it (`param_sep`) to another character". He did not specify any limitations in regards to character choice, so I changed it to a hyphen. The results of the change are described in my initial post.

**Comment by flaviocopes** [comment]
I have never tested with anything else than `:` or `;`, the two options we allow through Admin. I'll try with hyphens, but not sure if any char is supposed to work fine.

**Comment by flaviocopes** [comment]
I don't think using hyphens is ever going to work, or any other char that is not encoded when used as parameter.

**Comment by JeffStarr** [comment]
So only : or ; for param_sep, correct?

**Comment by rhukster** [comment]
those are tested, but other URL valid chars should work.  I think this needs to be tested with say `=`

**Comment by JeffStarr** [comment]
So I'm hearing flaviocopes saying, "I don't think using hyphens is ever going to work, or any other char that is not encoded".. and you are saying, "other URL valid chars should work".. sort of confused here..

**Comment by rhukster** [comment]
just not looked into it yet.  We've tested with `;` and `:` and nothing else.  I know we don't explicitly check for `:` or `;` but will need to investigate it to know why your char is not working.

**Comment by JeffStarr** [comment]
it's no so much any particular character i am concerned about, rather just some clarity in the documentation (and from the devs) regarding what can and can't be used for `param_sep`, if it even can be customized, which characters are allowed, any caveats, etc.

**Comment by w00fz** [comment]
You should change the `param_sep` if you know what you are doing. There are a lot of caveats and mostly it does come down to common sense and underline knowledge of what the param purpose is.

First of all, the param separator is meant to separate a key and a value in the URI string. Since we need a strong default value we purposedly used reserved characters (`:` by default, `;` if you have issues with it).

Aside from that, you have total freedom over it, but you should know what you are doing. For instance, if you set your param_sep to `e` your URI would look like `http://yoursite/subfolder/keyevalue`, you see how this is impossible for it to work, at which `e` point does the key ends and the value starts? 

On the other end, if you use param separators that are very unlikely to be used, like `|` or `_` or even multiple characters (that's allowed), like `-!-`, then you are good.

FYI, I also tested with emoji, and it works great:

```
/admin/notifications.json/task😱getNotifications
```

My advice, only touch it if you know what you are doing and you have a real need to changing it, otherwise there is no reason whatsoever :)

Hope this helps and if you'd like to contribute in making the docs better, [please go ahead, we would appreciate it!](https://github.com/getgrav/grav-learn/tree/develop/pages).

**Comment by JeffStarr** [comment]
Gosh that's swell advice, thanks!

**Comment by JeffStarr** [comment]
Just to keep this thread focused:

1. There is a bug when changing the value of `param_sep` to a hyphen, `-`. This is [confirmed by rhukster](https://github.com/getgrav/grav/issues/1039#issuecomment-246889157). Admin area breaks, et al.

2. Thanks to some astounding insight from "w00fz", there now are _three_ conflicting answers regarding which characters are allowed/recommended for `param_sep`:

- @flaviocopes says: "I don't think using hyphens is ever going to work, or any other char that is not encoded" (i.e., only encoded characters will work).

- @rhukster says: "other URL valid chars should work" (i.e., any valid URL character may work).

- @w00fz says: "you have total freedom over it" (i.e., any character or even string of characters will work, even emojis).

We know that hyphens used for `param_sep` break the admin area. We know that the config file enables users to change the value of `param_sep`. What we don't know -- at least not in any definitive sense -- is which characters work, and which are recommended by the Grav team.

Further, this priceless advice:

"..only touch it if you know what you are doing and you have a real need to changing it, otherwise there is no reason whatsoever"

Is nonsense. If the software provides an option that may be modified by the user, it should 1) be well documented, and 2) work properly. Currently neither of these criteria are met.

**Comment by w00fz** [comment]
It is not a bug, as I explained to you exhaustively above, you can use `-` only if you DON'T have any other `-` in the URI, which is unlikely. It is unlikely since we always concatenate with dashes and it's how all slugs look like on the web.

I think you are just reading what you want, frankly. None of our answers above are conflicting with each other.

I really don't have time to waste with this, especially since you haven't told us what you are trying to do and what's your valid reason for changing the param_sep in the first place. Either way I'll go through it with you once again.

You have total freedom in changing the `param_sep` to whatever you want. This is true, you can and you just did otherwise we wouldn't be here. It's a setting, change it with whatever you want. 
 
There are consequences, though, if you use a separator that doesn't make any sense, like `-` or `/` or an alpha-numeric character. I think this is a pretty easy concept to grasp and I explained to you above why it is so.

The above point just confirms what @flaviocopes, @rhukster and myself have said to you above:
* @rhukster: You can use any valid character ✅ 
* @w00fz: You have total freedom as long as it makes sense (see `e` param_sep example which is exactly like saying `-`) ✅ 
* @flaviocopes: Don't think you can use hyphens ✅ 

We cannot document what characters you can use, because you can use any of the UTF-8 characters available. And we cannot also document which characters you cannot use, because it is all based on your server setup and your preferences and your URLs.
What we can tell you is to use UNIQUE characters, don't use any of `a-z-0-9/i` characters, don't use `-`, don't use `/`, don't use anything that might show up in your URI. 

Bottom line is, why do you need to change this in the first place? `:` and `;` are working perfectly fine for everyone. Where is the portion of documentation that confuses you? Why don't you try to contribute in the docs and add more value to the `param_sep`, you have plenty of material in this issue.

If you are complaining that changing the `param_sep` breaks your admin, I can only tell you that we tested it and it doesn't, if you use a proper separator. So I can only assume you really didn't have a real use for changing it, otherwise you would know exactly why you had to change it and to what character.

Originally `param_sep` was introduced because we hardcoded the `:` but some servers running Apache had issues with it, so we made it a fully customizable setting. We don't have any logic in place to say what's a valid character and what's not, we want it to be like this and at your own discretion.

We also made it so that you can only pick either `:` or `;` from the admin, so that you can't really change to anything different than that. All you are talking here is for advanced users and if as advanced user you don't know why `-` shouldn't be used or why it breaks the URIs, then just don't change the field manually.

I really hope this answers all your questions.

And finally, you can always read the code  if that helps you better understanding how this all works ([Grav/Common/Uri.php#L359-L374](https://github.com/getgrav/grav/blob/develop/system/src/Grav/Common/Uri.php#L359-L374)).

Cheers.

**Comment by JeffStarr** [comment]
Lol, no need to freak out dude. I am only trying to help with a simple bug report, and maybe learn a little more about Grav in the process. So sorry if I offended your genius with my stupid questions.

**Comment by w00fz** [comment]
I don't believe there's any question that is stupid.

Anyway, you've got the attention of the whole team on the `param_sep` matter, I hope you now know why what you reported isn't a bug.

Apology accepted. 😉

**Comment by JeffStarr** [comment]
Actually, I'm thinking now that switching to Grav is a mistake. 

In 10 years working on the frontline with WordPress, I've never encountered such arrogance and attitude when trying to get help with something so simple.

Congrats.

**Comment by flaviocopes** [comment]
You opened the issue with:

> The default value ( : ) of param_sep is a reserved character according to RFC spec (more info). Fortunately Grav provides a way to change the default value via user/config/system.yaml.

RFC 3986:

```
2.2.  Reserved Characters

   URIs include components and subcomponents that are delimited by
   characters in the "reserved" set.  These characters are called
   "reserved" because they may (or may not) be defined as delimiters by
   the generic syntax, by each scheme-specific syntax, or by the
   implementation-specific syntax of a URI's dereferencing algorithm.
   If data for a URI component would conflict with a reserved
   character's purpose as a delimiter, then the conflicting data must be
   percent-encoded before the URI is formed.

      reserved    = gen-delims / sub-delims

      gen-delims  = ":" / "/" / "?" / "#" / "[" / "]" / "@"

      sub-delims  = "!" / "$" / "&" / "'" / "(" / ")"
                  / "*" / "+" / "," / ";" / "="

   The purpose of reserved characters is to provide a set of delimiting
   characters that are distinguishable from other data within a URI.
   URIs that differ in the replacement of a reserved character with its
   corresponding percent-encoded octet are not equivalent.  Percent-
   encoding a reserved character, or decoding a percent-encoded octet
   that corresponds to a reserved character, will change how the URI is
   interpreted by most applications.  Thus, characters in the reserved
   set are protected from normalization and are therefore safe to be
   used by scheme-specific and producer-specific algorithms for
   delimiting data subcomponents within a URI.

   A subset of the reserved characters (gen-delims) is used as
   delimiters of the generic URI components described in Section 3.  A
   component's ABNF syntax rule will not use the reserved or gen-delims
   rule names directly; instead, each syntax rule lists the characters
   allowed within that component (i.e., not delimiting it), and any of
   those characters that are also in the reserved set are "reserved" for
   use as subcomponent delimiters within the component.  Only the most
   common subcomponents are defined by this specification; other
   subcomponents may be defined by a URI scheme's specification, or by
   the implementation-specific syntax of a URI's dereferencing
   algorithm, provided that such subcomponents are delimited by
   characters in the reserved set allowed within that component.

   URI producing applications should percent-encode data octets that
   correspond to characters in the reserved set unless these characters
   are specifically allowed by the URI scheme to represent data in that
   component.  If a reserved character is found in a URI component and
   no delimiting role is known for that character, then it must be
   interpreted as representing the data octet corresponding to that
   character's encoding in US-ASCII.
```

So, `:` is perfectly valid separator for parameters and their values. 

We have it configurable because of an Apache on Windows bug with it, and we suggest to use `;`. That's it.

We never recommended using anything else, because yes we offer the option, but for this specific reason, not to allow fantasy URLs. Through Admin, that's what we offer: `:` and `;`.

You can see from that RFC description that non-reserved characters that are not encoded in the params or values strings will not work, because of the risk of duplicated and thus confusion when decoding the params, but this might be evident only when that character is present in the param/value as @w00fz already well explained.

**Comment by JeffStarr** [comment]
Yeah, I appreciate the response, but again what you are saying conflicts with what your team member repeats several times in this very thread, that _any valid character will work_ but only if you know what you are doing, lol. It's just getting too redundant now, although I do thank you @flaviocopes for taking the time to reply.

"We never recommended using anything else"

Um yeah read thru this thread, several times it's claimed that any other character or even strings of characters will work (even emojis). So again, conflicting information from the Grav team.

As I've explained elsewhere, it's all moot at this point anyway. My plan was to really dig in and get into Grav, help with documentation, learn the software, and contribute to the community. But now after being treated with such contempt by your other team member, I've changed my mind and decided to spend my time contributing elsewhere.

Software is only as good as the people behind it. After encountering your other team member on this thread, it's clear to me that Grav suffers from much more than a few random bugs.
