### ISSUE TITLE
Bug: Cannot use closing bracket `]` in regex via Admin Panel

### ISSUE THREAD

**Issue by Sommerregen** [getgrav/grav-plugin-admin#776]
I recently found a bug with regexes set via admin panel.

To reproduce this issue go to `admin/config/site`. Under "Custom Routes" use for example `/#(?<tag>[a-zA-Z0-9]+)/` as the alias and a route of your choice. Hit the save button and everything including closing bracket will be stripped of the regex. In other word it becomes `/#(?<tag>[a-zA-Z0-9`.

As far as I have inspected it, brackets like `[` and `]` should be escaped otherwise when sending the form they will be interpreted as array delimiters.

Setting the above regex manually in Grav site config works fine though. Only Admin Panel is affected.

**Comment by w00fz** [comment]
Yes the issue is exactly that, the route is the final field that gets sent to the server. It will have the `name` set to the alias and the `value` to whatever route.

```html
<input type="text" name="data[routes][/#(?<tag>[a-zA-Z0-9]+)/]" value="/go/here" />
```

This is all handled via JS dynamically so that the `name` and `value` get updated as you type in those two fields. 

The problem is I tried and I can't really escape those square brackets, otherwise they will be stored and interpreted by the regex as escaped, becoming just regular square brackets characters instead of regex ranges.

I had a look at how the form gets sent and it looks like it should be working fine:

![configuration site grav 2016-09-15 11-42-00](https://cloud.githubusercontent.com/assets/11734/18562661/8af4ec1a-7b39-11e6-9248-c2dbaa33396e.png)

So I wonder if we are doing something wrong in cycling through the post and not treating properly the keys.

**Comment by Sommerregen** [comment]
Hi @w00fz ,

I thought about it a bit and the only solution what came into my mind is the following: Escape `[` and `]` on the client side and send the form to the server. On the server side only unescape those two characters.If that is done consistently there should be no problem. Even when the bracket is escaped beforehand, it will gets escaped twice, then sent to the server and unescaped once. What do you think?

**Comment by w00fz** [comment]
Ok I have it cleaning up the POST once received. It is a bit convoluted because it's a lot of back and forth and manipulation that doesn't feel quite safe. However, Array field is probably the only one that has a dynamic `name` generation based on input data, so it should be ok.

I tested this and seems fine now, if you'd like to give it a try that would be appreciated.
