### ISSUE TITLE
Page Ordering Disabled

### ISSUE THREAD

**Issue by metadiv** [getgrav/grav-plugin-admin#786]
I cant seem to get the admin ordering fields to work for pages in a collection of prefixed folders.

**Page Order**
Parent setting order, ordering disabled

appears above the stack of page name 'advanced' tab.

![image](https://cloud.githubusercontent.com/assets/1914218/18640708/3897f7fe-7e91-11e6-9871-020e39e81f16.png)

In the parent page's markdown file I am using :

``` markdown
---
title: 'page title'
content:
    items: '@self.children'
    order:
        by: default
        dir: asc
---
```

Previously this worked but I have recently upgraded my site to the latest version of Grav and Admin.

I can confirm that manually modifying the folders prefixes does re-orders them correctly in the front end, but as I need to hand this site off to less techy colleagues it would be great to give them control from the admin ui.

Any suggestions please?

**Comment by rhukster** [comment]
This looks like a bug.  Will get it looked at.  Thanks.!

**Comment by metadiv** [comment]
@rhukster Yes it worked on the previous build I had before I upgraded.

One other question. Do you know if its possible to setup either the entire system or via a page type blueprint to automatically enable folder prefixing even if the page created is the first sibling in its parent?

**Comment by rhukster** [comment]
Ok, there is a bug here, but it's still not going to work for you until you remove the `items:` section of the frontmatter.  This is because you cannot manually reorder if you are setting the `content.items` manually. Manual reorder is just for an arbitrary collection of page folders in a particular directory: https://github.com/getgrav/grav-plugin-admin/blob/develop/themes/grav/templates/forms/fields/order/order.html.twig#L17

Imagine if you had a ` content: items: '@taxonomy....` collection.  This cannot be reordered of course.

This has not changed since Feb 1st.  There was a bug where this logic was not being tested properly.  Perhaps that is the version you updated from? If so it was a buggy version, that is now fixed.

**Comment by metadiv** [comment]
@rhukster Thanks for the explanation. I can confirm removing the item: self.children from the parent works. 

Can I ask though my 2nd question, is there a way to enable folder prefixing as a default, either int he site settings or as a blueprint function?

**Comment by rhukster** [comment]
Please open a new issue for this question. Thanks!
