### ISSUE TITLE
Grav admin cache on planethoster mutualized servers

### ISSUE THREAD

**Issue by maximelebreton** [getgrav/grav-plugin-admin#795]
On [planethoster mutualized plans](https://www.planethoster.net/en/World-Hosting), cache systems aren't supported (except file system).

But if I can see perf improvements when I use file cache system on the front-end,
the back-end is still very slow (about 5-10 seconds to load a simple page, and 1 minute for a page with 10 `filepickers`...).

Have you any ideas to improve back end performances in these cases?

note: with wordpress on the same host plan, the back-end is fast.

Thanks!

**Comment by rhukster** [comment]
It could just be a slow filesystem.  Some hosting plans have shared 'networked' filesystems, and as Grav is filesystem based, a fast, local, filesystem is needed for optimum performance.

I see they promise unlimited SSD space, that sounds to me like some kind of shared filesystem, so that's probably it.  If that's the case, there's nothing we can really do about it. Pretty hard for me to tell without actually testing on the hosting provider's own servers though.

**Comment by flaviocopes** [comment]
Might definitely be a slow filesystem. Did you try running your site locally (just move the `user/` folder to a Grav site you have installed local) and see the difference in speed?

**Comment by maximelebreton** [comment]
@rhukster absolutely, my client was on a old classic hard drive server, and since Planethoster migrated the plan on a SSD server, it's about 10x faster.

**Comment by maximelebreton** [comment]
> Grav is filesystem based, a fast, local, filesystem is needed for optimum performance.

So maybe this should be in the docs?
https://learn.getgrav.org/basics/requirements
