### ISSUE TITLE
In the System Info page, if ionCube is installed, its status does not fit into the page

### ISSUE THREAD

**Issue by ghost** [getgrav/grav-plugin-admin#844]
В панели управления, в разделе настройки - сведения о системе, строка выходит за зримые поля:
"with the ionCube PHP Loader (enabled) + Intrusion Protection from ioncube24.com..."
А в остальном все Cool!

**Comment by flaviocopes** [comment]
Translation: 
In Control Panel, under Settings - System Information, line beyond the visible field " with the ionCube PHP Loader (enabled) + Intrusion Protection from ioncube24.com" 

I don't understand the question, that means ionCube is enabled in your PHP install. Is it giving problems to Grav?

**Comment by scaur** [comment]
31.10.2016, 18:50, "Flavio Copes" <notifications@github.com>:Translation:In Control Panel, under Settings - System Information, line beyond the visible field "with the ionCube PHP Loader (enabled) + Intrusion Protection from ioncube24.com"I don't understand the question, that means ionCube is enabled in your PHP install. Is it giving problems to Grav?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread. Good day, no matter in appearance design, the text I mentioned above, just does not fit into the page. --Sincerely,Andrey Viktorovich

**Comment by flaviocopes** [comment]
Ok, we don't directly manage that output, since it's the result of calling `phpinfo()`. Leaving it open as I need to install ionCube to replicate it, or if someone has it installed and sees the problem, can check if it's a quick CSS fix.

**Comment by scaur** [comment]
Okey01.11.2016, 20:58, "Flavio Copes" <notifications@github.com>:Ok, we don't directly manage that output, since it's the result of calling phpinfo(). Leaving it open as I need to install ionCube to replicate it, or if someone has it installed and sees the problem, can check if it's a quick CSS fix.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




-- С уважением, Андрей Викторович
