### ISSUE TITLE
error: fetch failed Crikey ...

### ISSUE THREAD

**Issue by immertroll** [getgrav/grav-plugin-admin#869]
Currently Grav Admin throws an error which is really unclear.

There is no change in configuration, plugins or something else.
![image](https://cloud.githubusercontent.com/assets/13539454/20459371/44b83ac2-aebf-11e6-9e0c-34c5c2e965ce.png)

**Comment by rhukster** [comment]
What version of Grav and Admin plugin are you running?

**Comment by immertroll** [comment]
Hello @rhukster ,

thank you for your response. My webhoster had a problem with php configuration. It's now fixed. Sorry.

**Comment by flaviocopes** [comment]
Do you know which problem exactly? If it happens again to someone else, we can point to the solution you used

**Comment by tranduyhung** [comment]
I have the same problem on only 1 website. The site had Grav v1.1.9 and Admin v1.2.5. I have just updated to Grav v1.1.11 and Admin v1.2.7. This error sometimes shows up so it is very difficult to check.

**Comment by phideas** [comment]
Same problem on 1 website. Running latest Grav + Admin Panel.

**Comment by flaviocopes** [comment]
Does the PHP error log contain any message that could be related?

**Comment by phideas** [comment]
IDK. This bug didn't show up last couple of days.

**Comment by phideas** [comment]
Noticed the bug again. It happens after pushing new code to webserver. After clear-cache on server the bug disappears.

**Comment by flaviocopes** [comment]
@phideas just happens locally, or also on the webserver?

**Comment by immertroll** [comment]
Hello. Sorry for my late answer. My webhoster had upgraded from PHP 5.6 Standard to 5.6.
I got the errors during this update.

**Comment by blancblanc** [comment]
I'm having the same issue after moving grav to a different hosting provider. There are a lot of variables that are different from my original provider, so I'm unclear on how to troubleshoot.

**Comment by phideas** [comment]
Didn't noticed the bug locally. My local machine runs PHP5, the server runs on PHP7. I suspect it can be cache related.

**Comment by blancblanc** [comment]
I moved my grav directory from a server running PHP 5.6.29 to a server running PHP 5.6.6, but with Debian - missing a few extensions. I manually included all the required ones listed it the documentation, but I'm suspicious something else is missing specifically for the admin plugin...

**Comment by rhukster** [comment]
Can you guys please use Chrome, and open up the "**Developer Tools**", then in there, select the "**Network**" Tab.  In there filter only the "**XHR**" requests.  Then reload the page.  That should show which of the requests is causing the problem.

![2017-01-12 at 10 44 am](https://cloud.githubusercontent.com/assets/1084697/21901271/48c40942-d8b4-11e6-9025-4ec701dd30f9.png)

Then you can click on the request in question and choose the "**Preview**" tab:

![2017-01-12 at 10 46 am](https://cloud.githubusercontent.com/assets/1084697/21901311/68d84d6a-d8b4-11e6-8283-9df15ef839cd.png)

This might help us isolate what is going on.

One thing to try if you haven't already is to disable verify_peer in GPM:

```
gpm:
  verify_peer: false
```

**Comment by blancblanc** [comment]
@rhukster Followed your instructions - preview reveals the grav error page with the following message: 

> PHP Startup: Unable to load dynamic library '/usr/local/lib/php-5.6.6-amd64/lib/php/extensions/no-debug-non-zts-20131226/php_zip.dll' - /usr/local/lib/php-5.6.6-amd64/lib/php/extensions/no-debug-non-zts-20131226/php_zip.dll: cannot open shared object file: No such file or directory

Looks like the zip extension is causing the problem? When I run get_loaded_extensions in PHP on that server though, zip is included in the output...

**Comment by rhukster** [comment]
@blancblanc you are definitely seeing a PHP configuration issue error. That error is during PHP startup and not even at Grav yet.

Basically your PHP is configured to use a PHP library that doesn't exist.  You probably need to edit your php.ini (or appropriate sub ini file) and remove that entry.  maybe it's added later with the correct path, and that's why it actually does show up, but the bad entry is enough to trigger the message.

**Comment by blancblanc** [comment]
@rhukster Thank you so much for your guidance!

**Comment by timbednar** [comment]
Hi -- I'm having a hard time as well tracking down problem. I followed your instructions. And I see this

`{"error":{"type":"Whoops\\Exception\\ErrorException","message":"Grav\\Plugin\\AdminPlugin::Grav\\Plugin\\{closure}(): Failed opening required '\/home\/webdevkan\/public_html\/user\/plugins\/admin\/classes\/admincontroller.php' (include_path='.:\/opt\/alt\/php56\/usr\/share\/pear:\/opt\/alt\/php56\/usr\/share\/php')","file":"\/home\/webdevkan\/public_html\/user\/plugins\/admin\/admin.php","line":121}}`

Now the problem is that on the account where this is installed -- for some reason the root directory is not /home/ but /home3/ which is I think the problem. 

I'm a bit lost on how fix this -- it seems like a server/php config problem where the correct path is not being used. I appreciate any help.

/Tim

**Comment by tomceek** [comment]
Got this error and stuck for now, need help where to search for problem or how to fix.

Tried filter only the "XHR" requests for more info as in example but no info at all.

Attaching image:
![tempsnip](https://user-images.githubusercontent.com/30144585/42423264-4ca4e7be-8300-11e8-8562-aab9558f4583.png)

thanks in advance
