### ISSUE TITLE
Options in site.yaml not shown in Admin Panel

### ISSUE THREAD

**Issue by carlu93** [getgrav/grav-plugin-admin#873]
Hey guys,

thanks for all the hard work you're investing in this project. I'm really enjoying grav and all the possibilities. One thing really bothering me is, that extra options in the site.yaml file are not shown in the Admin Panel under Site.
Would it be possible to show all the content in the Admin Panel? I'm using the "Deliver" Skeleton and it took me hours to realize, that like half of the content is missing in the admin panel.
In my opinion, because of the indentation, it might not be that hard to show all those options without some fancy stuff. 

Thank you so much in advance!

**Comment by rhukster** [comment]
The site.yaml is intended to be a bit of a freeform location for data and values.  In order to have the appropriate forms to edit/save this in the admin you have to update the site.yaml blueprints file.   It's possible to do using the Grav form syntax to extend the existing blueprint, but not something that is commonly done.  As those settings are usually set during the development phase, and not messed with much after.

**Comment by carlu93** [comment]
okay. thank you for clearing that up! :) I'll try to look into it.

**Comment by flaviocopes** [comment]
@carlu93 see https://learn.getgrav.org/forms/blueprints/example-config-blueprints

**Comment by carlu93** [comment]
Great. Thanks a lot!
