### ISSUE TITLE
Server Error after Update to current stable

### ISSUE THREAD

**Issue by BugHunter2k** [getgrav/grav-plugin-admin#894]
Hi there,

I've just updated grav and admin-plugin and got this error:
<pre>
Server Error
Sorry, something went terribly wrong!

0 - The "Grav\Plugin\AdminTwigExtension" extension is not enabled in "dashboard.html.twig" at line 1.

For further details please review your logs/ folder, or enable displaying of errors in your system configuration.
</pre>

The error went away after clearing the cache via grav-console.

**Comment by rhukster** [comment]
Yah, we've seen this very sporadically with this upgrade.  Unfortunately it's appears to be a 'timing' issue with the way the new classes in the admin plugin get overwritten and then cached.  We've actually added a slight 'pause' after installation in an attempt to resolve this for future updates, but because this is actually something that is happening based on the 'old' version of the admin, there's not a whole lot we can do.   Also it's very hard for us to reproduce. Performing the same steps with a consistent base install, sometimes causes it and sometimes not.

Anyway, as you say, a clearing of cache **does** fix it.  Also if you can't reach the CLI for some reason then going to `/admin/dashboard/task:clearCache` results in a page that does render (although you will get a missing security token message), but from there you can click the **Clear Cache** button in the admin, which fixes it also.

**Comment by ericloyd** [comment]
I, too, fell prey to this on a 1.17 -> 1.2 upgrade.  Clearing cache as outlined in previous step, then continuing to check updates (again) and then actually performing them allowed me to continue.

Thanks!
