### ISSUE TITLE
Unknown "array_unique" filter in "forms/fields/taxonomy/taxonomy.html.twig"

### ISSUE THREAD

**Issue by tomet** [getgrav/grav-plugin-admin#897]
When i want to edit a page i always get this error message:

Unknown "array_unique" filter in "forms/fields/taxonomy/taxonomy.html.twig" at line 8.

I am new to grav, but to me it seem's that there is no twig filter named "array_unique".

**Comment by flaviocopes** [comment]
Hi @tomet this is quite strange as we have that line since a few months and I never saw this problem. It's an implicit filter. I explicitly added it to Grav, if you can check this edit and apply it to your site: https://github.com/getgrav/grav/commit/e40bed5be203d710c73f3fede9ca3a23bae69788 and tell me if the problem is fixed

**Comment by tomet** [comment]
If i insert this line in TwigExtension.php it is working.

I tried the filter 'array_unique' in my custom theme and i get the same error (before i modified TwigExtension.php). I also searched the sourcecode of my grav installation for the usage of the filter and i only found it in line 8 of taxonomy.html.twig ;-)

**Comment by flaviocopes** [comment]
Ok thanks for testing, keep that line in, will be part of the next Grav release 👍

**Comment by tomet** [comment]
Thank you!

**Comment by tomet** [comment]
Sorry! It was my fault! I had system.twig.undefined_filters: false in my user/config/system.yaml file!

**Comment by flaviocopes** [comment]
Oh good you found the cause of the problem. Also good that now it's a "defined" filter, so this problem won't occur any more.
