### ISSUE TITLE
after activate theme Learn2 - error

### ISSUE THREAD

**Issue by 1Cmobile** [getgrav/grav-plugin-admin#933]
RuntimeException (400)
Template "default.html.twig" is not defined.
  COPY
Stack frames (16)
15
RuntimeException 
…/system/src/Grav/Common/Twig/Twig.php352
14
Twig_Error_Loader 
…/vendor/twig/twig/lib/Twig/Loader/Chain.php139
13
Twig_Loader_Chain getCacheKey
…/vendor/twig/twig/lib/Twig/Environment.php329
12
Twig_Environment getTemplateClass
…/vendor/twig/twig/lib/Twig/Environment.php418
11
Twig_Environment loadTemplate
…/vendor/twig/twig/lib/Twig/Environ

**Comment by flaviocopes** [comment]
The reason of the problem is you have a `default.md` page in your site, but the theme does not support that page template.

Not all themes in Grav can be swapped one with another, because some are very specialized. 
Like Learn2, which does not support a `default` page type, but just `docs` and `chapter` page types, because it's building a documentation site and it was decided to just provide support for those 2 page types.

See 

https://getgrav.org/blog/traditional-cms-platforms-and-grav
https://learn.getgrav.org/basics/basic-tutorial

for more information on why sometimes themes are not interchangeable.
