### ISSUE TITLE
Runtime Exception bei Theme Medium

### ISSUE THREAD

**Issue by icoglu** [getgrav/grav-plugin-admin#964]
If i install and activate the them Medium over grav admin ui, then i become the following exception:

RuntimeException (400)
Template "item.html.twig" is not defined.

  $error_msg = $e->getMessage();
            // Try html version of this template if initial template was NOT html
            if ($ext != '.html' . TWIG_EXT) {
                try {
                    $page->templateFormat('html');
                    $output = $this->twig->render($page->template() . '.html' . TWIG_EXT, $twig_vars);
                } catch (\Twig_Error_Loader $e) {
                    throw new \RuntimeException($error_msg, 400, $e);
                }
            } else {
                throw new \RuntimeException($error_msg, 400, $e);
            }
        }
 
        return $output;
    }

...

**Comment by diomed** [comment]
I believe this is issue to post on theme's github issues, not here:

https://github.com/mblode/grav-theme-medium

**Comment by flaviocopes** [comment]
Quick tip - the theme does not support `item` page types (`item.md` pages). It seems to have the `post` page type instead: https://github.com/mblode/grav-theme-medium/tree/develop/templates

(every theme may decide to implement pages differently, that's why switching a theme to another is not always an immediate task, depends on the theme)
