### ISSUE TITLE
Check write access to folders

### ISSUE THREAD

**Issue by ulab** [getgrav/grav-plugin-admin#975]
Before I even got to see the first grav page I had to look through the webservers error log since I was only getting a white page.

It was missing write access to the following two folders - which both are required to show me the missing write access for more folders ;):

cache/
user/config/

After installing the admin panel, grav was not able to create the first admin user because of another missing write access for: 

user/accounts

This one should probably be added to the check on the installation error page, while the first two need to check even earlier.

Grav v1.1.16 - Admin v1.2.12

PS: Yes, I know I should've unzipped the archive using the right user / changed to the right user when installing like it's explained in the [Requirements -> Permissions section](https://learn.getgrav.org/basics/requirements#permissions), but this might confuse other users on systems with less access too.

**Comment by flaviocopes** [comment]
Good suggestions for a better first-time experience on a problematic permissions setup

**Comment by mahagr** [comment]
Great way to test this is to unzip skeleton and making all files and folders read only.

There are a few things we should consider:

* We should make sure that Grav skeletons catch and deal with file permission issues instead of throwing uncaught exception
* Plugins should be able to hook into problems event (new one) and add their own checks when Grav checks for possible issues
* Problems event could also be configured to run on uncaught exceptions allowing simple diagnosis before displaying error

**Comment by ulab** [comment]
> Plugins should be able to hook into problems event (new one) and add their own checks when Grav checks for possible issues (you don't need user/accounts at all unless login plugin is installed)

I'm not deep enough into Grav coding, but I'd try to avoid a long list of checks that are done every time someone calls the page for performance reasons unless it's really necessary.

A global "check for problems"  function for the admin where plugins can hook into might be a nice touch, but in the case of the user generation a single check before saving or even when displaying the form might have been enough if a possible is displayed with a more user friendly error message instead of simply throwing an exception.

**Comment by rhukster** [comment]
The "problems" plugin is smart enough to write a small file in the cache folder so that it doesn't check things every page load, only when cache is cleared.

**Comment by dbfin** [comment]
Yes, and special thanks to @ulab. Without your making this issue, I would stuck at an empty page for much longer! Cheers!

**Comment by mahagr** [comment]
@dbfin I agree with you, though there is some need to have writable folders, most notably for caching, image generation and data from the forms, which you just cannot get rid of. What comes to automatic updates, you can do those from the CLI.

I am running the web server as a different user and everything works just fine as long as you allow certain folders to be writable. The biggest issue is caching, which does by default need to be cleared before you can run CLI commands or see a web page -- there's certainly some room for improvement in there.

If caching in such instances is slightly improved, I would not see why you couldn't fully run Grav by using 2 different users. It is just harder to set up configuration like that because of you need to deal with permissions. Also, things like priming cache cannot work unless you use the same user (which is why I usually use `sudo` in the command line).

**Comment by dbfin** [comment]
@mahagr The way I found to deal with such problems when you need to work on some directories from CLI under your username (flush cache etc.) and allow webserver write into the same directories (cache things etc.) is by using ACL. There are a few ways. For example, change the owner of cache/ to the webserver, and add yourself write permissions via ACL (both to existing files and as a default permission). Or vice versa. For system/, for example, you own the directory, and add ACL read-only permissions for the webserver. 

ACL permissions are much more flexible, but you should understand them much better than regular *nix permissions. Here is a catch, for example. Suppose, you add ACL permissions to a directory that forbids the server to delete any files in it, but it can create files (these standard permissions are the same permission w, in ACL you can distinguish them). Now, if a server creates a file, it cannot delete it then. But, what it can do, since it owns it, it can, first, change ACL permissions of the file, and then just delete it. There are more examples like that on the internet. So, if you really want to protect a folder, make sure you own it and all files, and give the webserver just ACL read permissions. 

The combination of ownership and standard + ACL permissions is quite flexible. So, I think, running any commands under root is not the best idea.

**Comment by mahagr** [comment]
You cannot use ACL for that because of there's no write access for the files written in CLI <-> web to each other. So if you're running with different permissions in CLI, you will never be able to do tasks from CLI to clear cache etc (unless you use sudo).
