### ISSUE TITLE
Whoops breaking with xxxx "loaded already" 

### ISSUE THREAD

**Issue by marktaylor46** [getgrav/grav-plugin-admin#980]
Please see screenshots below - we had a similar issue in Gantry 5 which was fixed
https://github.com/gantry/gantry5/issues/1821

![2017-02-16_17-06-06](https://cloud.githubusercontent.com/assets/11683218/23032979/467f065c-f46e-11e6-9b06-263ae79b9432.png)

![2017-02-16_17-15-02](https://cloud.githubusercontent.com/assets/11683218/23033004/65413510-f46e-11e6-8846-01c53ce23b10.png)

![2017-02-16_17-15-02](https://cloud.githubusercontent.com/assets/11683218/23033017/75cdc45c-f46e-11e6-9f4d-720b6c84cce1.png)

**Comment by w00fz** [comment]
This happens because of misconfiguration in PHP but also because Whoops handles core warnings which shouldn't.
@mahagr is going to look at this so that Whoops won't trip on this.

There is also a fix I just applied so that you will now get the actual error in the message notification rather than that full HTML nonsense.

**Comment by mahagr** [comment]
https://github.com/getgrav/grav/commit/14bde9f31f5cb2275f15bce406cb407cae05f374
